#!/usr/bin/env python
"""Small but REAL fixture tree for the equal-budget ladder analysis (scripts/equal_budget/eqb_metrics.py,
analyze_ladder.py, tests/test_eqb_metrics.py).

    python scripts/equal_budget/make_fixtures.py [--root DIR] [--systems gateway lta300 lta300_prodrate] [--force]

Every fixture run is produced by the ACTUAL production engines through the production driver's own
functions (run_ladder.save_grid, run_ladder.job_list, run_ladder.lta_run_job, gateway run_job), so the
files have exactly the production layout and save-grid logic; only the budget, the N ladder, the seeds
and (LTA) the warm-up / burn-in / FR start / genealogy window are reduced.

  <root>/results/equal_budget_v2/<out_dir>/N<N>/s<seed>_<method>.npz     (+ ledger.csv)
  <root>/configs/{gateway_fixture.json, lta_300K_fixture.json, lta_300K_fixture_prodrate.json}
                                                                        (production schema, reduced values)

Gateway: h unchanged (2.5e-5), N {8, 2, 1}, B = 8 x 2e6 (T_N = 50, 200, 400), seeds 8100-8102.
LTA 300 K: h unchanged (2e-4), N {4, 2, 1}, B = 4 x 40000 (T_N = 8, 16, 32), warm-up / burn-in / FR start
2000 steps (0.4 t.u.), genealogy window 1 t.u., FR rate 40 (the production 0.2 never fires at N <= 4 in so short a
run: the walkers sit in distinct bins, the recentred score is ~0), seeds 30000-30002.
LTA 300 K at the PRODUCTION FR rate 0.2 ('lta300_prodrate', system lta300, out_dir lta_T300_prodrate): N {2, 1}, B = 2 x
40000 (T_N = 16, 32), same reduced warm-up / burn-in / FR start / window, seeds 30000-30002.  Its FR arms realise NO
death (the production small-N regime: FR arm == ABF arm bitwise), so the pipeline's FR-inactivity marking is tested.
n_steps(N) is a multiple of 200 at every N, so the 200 uniform budget fractions u = k/200 are exact saves (as in
production).
CPU only (CUDA_VISIBLE_DEVICES=""), single-threaded numba.
"""
import argparse
import copy
import csv
import json
import os
import sys
import time

os.environ["CUDA_VISIBLE_DEVICES"] = ""
for _k in ("NUMBA_NUM_THREADS", "OMP_NUM_THREADS", "MKL_NUM_THREADS", "OPENBLAS_NUM_THREADS"):
    os.environ[_k] = "1"
os.environ.setdefault("NUMBA_CACHE_DIR", os.path.expanduser("~/.cache/numba_eqb_dev"))

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "src"))
import run_ladder as RL  # noqa: E402  (production driver: save grid, job list, LTA adapter)

DEFAULT_ROOT = os.environ.get(
    "EQB_FIXTURE_ROOT",
    "/tmp/claude-1008/-home-zheyuanlai-ABF-Fisher-Rao/b25e8a63-d0d8-4935-af2b-7d50d5f3ea3b/scratchpad/analysis/fixtures")

FIXTURES = {
    "gateway": dict(
        system="gateway", production="gateway_production.json", fixture="gateway_fixture.json",
        N_ladder=[8, 2, 1], N_coarse=[8, 1], B=8 * 2_000_000, n_seeds=3, engine_overrides={}),
    "lta300": dict(
        system="lta300", production="lta_300K_production.json", fixture="lta_300K_fixture.json",
        N_ladder=[4, 2, 1], N_coarse=[4, 1], B=4 * 40_000, n_seeds=3,
        engine_overrides=dict(warmup_steps=2000, burn_in_steps=2000, fr_start_steps=2000, genealogy_window_tu=1.0,
                              fr_rate=40.0)),
    "lta300_prodrate": dict(
        system="lta300", production="lta_300K_production.json", fixture="lta_300K_fixture_prodrate.json",
        out_dir="lta_T300_prodrate", N_ladder=[2, 1], N_coarse=[2, 1], B=2 * 40_000, n_seeds=3,
        engine_overrides=dict(warmup_steps=2000, burn_in_steps=2000, fr_start_steps=2000, genealogy_window_tu=1.0)),
}


def fixture_config(name):
    """Production config with the reduced budget / ladder / seeds (same schema)."""
    spec = FIXTURES[name]
    system = spec["system"]
    P = json.load(open(os.path.join(ROOT, "configs", "equal_budget_v2", spec["production"])))
    F = copy.deepcopy(P)
    F["_frozen"] = ("FIXTURE (not a production config): " + spec["production"]
                    + " with reduced B, N ladder, seeds"
                    + (" and LTA warm-up/burn-in/FR start/window" if system != "gateway" else "")
                    + (" and FR rate" if "fr_rate" in spec["engine_overrides"] else "")
                    + "; generated by scripts/equal_budget/make_fixtures.py")
    F["_fixture_of"] = spec["production"]
    F["_fixture_name"] = name
    if spec.get("out_dir"):
        F["out_dir"] = spec["out_dir"]
    F["B"] = int(spec["B"])
    F["N_ladder"] = list(spec["N_ladder"])
    F["N_coarse"] = list(spec["N_coarse"])
    F["seeds"] = list(P["seeds"][:spec["n_seeds"]])
    F["engine_cfg"] = dict(P["engine_cfg"], **spec["engine_overrides"])
    if system != "gateway":
        F["engine_cfg"]["budget"] = int(spec["B"])          # lta make_cfg: n_steps = budget // N
    F["anchor"] = dict(N0=max(spec["N_ladder"]), T0=spec["B"] // max(spec["N_ladder"]) * float(P["engine_cfg"]["h"]))
    for N in F["N_ladder"]:
        n = F["B"] // N
        assert n * N == F["B"] and n % 200 == 0, (system, N, n)
    return F


def run_fixture(name, root, force=False):
    F = fixture_config(name)
    system = FIXTURES[name]["system"]
    cfg_dir = os.path.join(root, "configs")
    os.makedirs(cfg_dir, exist_ok=True)
    cfg_path = os.path.join(cfg_dir, FIXTURES[name]["fixture"])
    json.dump(F, open(cfg_path, "w"), indent=1)
    P = dict(F, system_key=system)
    E = RL.engine(system)
    res_root = os.path.join(root, "results", "equal_budget_v2")
    ledger = os.path.join(res_root, F["out_dir"], "ledger.csv")
    os.makedirs(os.path.dirname(ledger), exist_ok=True)
    new = not os.path.exists(ledger)
    rows = []
    with open(ledger, "a", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=["system", "N", "seed", "method", "n_steps", "status", "wall_s",
                                           "peak_rss_mb", "n_force_evals", "finished_utc"])
        if new:
            w.writeheader()
        for (N, seed, method, n_steps) in RL.job_list(P, "ladder"):
            path = os.path.join(res_root, F["out_dir"], f"N{N}", f"s{seed}_{method}.npz")
            if force and os.path.exists(path):
                os.remove(path)
            t0 = time.time()
            if system == "gateway":
                res = E.run_job(P["engine_cfg"], method, N, seed, n_steps, path, save_steps=RL.save_grid(P, n_steps),
                                checkpoint_every_s=float(P.get("checkpoint_every_s", 600.0)))
            else:
                res = RL.lta_run_job(E, P, method, N, seed, n_steps, path)
            r = dict(system=system, N=N, seed=seed, method=method, n_steps=n_steps, status="complete",
                     wall_s=float(res.get("wall_s", time.time() - t0)), peak_rss_mb=float(res.get("peak_rss_mb", float("nan"))),
                     n_force_evals=int(res.get("n_force_evals", -1)),
                     finished_utc=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()))
            w.writerow(r); fh.flush()
            rows.append(r)
            print(f"  {system} N {N} seed {seed} {method}: n_steps {n_steps} wall {r['wall_s']:.2f} s "
                  f"({time.time() - t0:.1f} s incl. load/compile)", flush=True)
    return cfg_path, rows


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=DEFAULT_ROOT)
    ap.add_argument("--systems", nargs="*", default=list(FIXTURES), choices=list(FIXTURES))
    ap.add_argument("--force", action="store_true", help="re-run (delete) existing fixture results")
    a = ap.parse_args(argv)
    out = {}
    for s in a.systems:
        print(f"fixture {s} -> {a.root}", flush=True)
        out[s] = run_fixture(s, a.root, a.force)[0]
    print(json.dumps(out, indent=1))
    return out


if __name__ == "__main__":
    main()
