#!/usr/bin/env python
"""Small but REAL fixture tree for the mechanism-cell analysis path (scripts/equal_budget/{analyze_ladder,
plot_config,plot_synthesis,audit_completeness}.py --system gateway_family; scripts/mechanism/cross_cell.py).

    python scripts/mechanism/make_cell_fixtures.py [--root DIR] [--cells EXP/VARIANT ...] [--workers 8] [--force]

Every production cell config (configs/mechanism/cells/, scripts/mechanism/make_cell_configs.py) is reduced the way
scripts/equal_budget/make_fixtures.py reduces the equal-budget ladders -- budget B = 8 x 2e6 walker-steps, N ladder
{8, 2} (T_N = 50, 200 at h 2.5e-5), seeds 8100-8102; h, every engine knob, the model fields, thresholds and the save
grid rule (run_ladder.save_grid: 200 uniform + 24 log u + physical checkpoints) unchanged -- and its runs are made by
the REAL engines:
  reuse cells (alpha1, lam1: engine_version gateway_ladder_numba/2)  src/gateway_ladder_numba.run_job with the
      equal-budget gateway production engine_cfg (no model fields), into ONE shared tree <root>/results/eqb_gateway
      (both cells read it, as production does);
  every other cell (gateway_family_numba/1)  src/gateway_family_numba.run_job with the cell's engine_cfg, into
      <root>/results/mechanism/<experiment>/<variant>.
Writes <root>/configs/cells/<experiment>/<variant>.json (fixture configs: absolute results_dir / analysis_dir /
fig_dir / reference_file / ledger under <root>, '_fixture_of' = the production cell config), the ledgers in the
PRODUCTION layout (new-engine cells: ONE <root>/results/mechanism/<experiment>/ledger.csv per experiment with
scripts/mechanism/run_cells.py's columns experiment, variant, ...; the reuse tree: run_ladder's <root>/results/
eqb_gateway/ledger.csv), the reuse-gate record of the reuse cells (scripts/mechanism/reuse_gate.py on the fixture
files: gateway_family_numba at alpha 1, lam 1 vs the gateway_ladder_numba fixture files, every fixture N, both arms;
<root>/reuse_gate/reuse_gate.json) and the frozen references (scripts/mechanism/build_references.py --cells-root
<root>/configs/cells) into <root>/references.  Default root: the session scratchpad (MECH_FIXTURE_ROOT overrides).
CPU only, numba single threaded per job, at most --workers parallel jobs.  FIXTURE DATA: tiny budgets, never
production evidence.
"""
from __future__ import annotations

import argparse
import copy
import csv
import json
import os
import sys
import time

os.environ["CUDA_VISIBLE_DEVICES"] = ""
for _k in ("NUMBA_NUM_THREADS", "OMP_NUM_THREADS", "MKL_NUM_THREADS", "OPENBLAS_NUM_THREADS"):
    os.environ[_k] = "1"
os.environ.setdefault("NUMBA_CACHE_DIR", os.path.expanduser("~/.cache/numba_mech"))

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "src"))
sys.path.insert(0, os.path.join(ROOT, "scripts", "equal_budget"))
import make_cell_configs as MC  # noqa: E402
import run_cells as RC  # noqa: E402  (the production ledger layout of the new-engine cells)
import run_ladder as RL  # noqa: E402  (the production save-grid rule)

DEFAULT_ROOT = os.environ.get(
    "MECH_FIXTURE_ROOT",
    "/tmp/claude-1008/-home-zheyuanlai-ABF-Fisher-Rao/b25e8a63-d0d8-4935-af2b-7d50d5f3ea3b/scratchpad/mech/pipeline/fixtures")
FIX_N = [8, 2]
FIX_B = 8 * 2_000_000
FIX_SEEDS = 3
LEDGER_FIELDS = ["system", "N", "seed", "method", "n_steps", "status", "wall_s", "peak_rss_mb", "n_force_evals",
                 "finished_utc"]


def fixture_cell(P, root):
    """A production cell config reduced to the fixture budget / ladder / seeds, located under ``root``."""
    F = copy.deepcopy(P)
    exp, name = P["experiment"], P["cell"]
    F["_frozen"] = (f"FIXTURE (not a production config): configs/mechanism/cells/{exp}/{name}.json with reduced B, "
                    f"N ladder and seeds; generated by scripts/mechanism/make_cell_fixtures.py")
    F["_fixture_of"] = f"configs/mechanism/cells/{exp}/{name}.json"
    F["B"] = FIX_B
    F["N_ladder"] = list(FIX_N)
    F["N_coarse"] = list(FIX_N)
    F["seeds"] = list(P["seeds"][:FIX_SEEDS])
    F["anchor"] = dict(N0=max(FIX_N), T0=FIX_B // max(FIX_N) * float(P["engine_cfg"]["h"]))
    F["T_N"] = {str(N): (FIX_B // N) * float(P["engine_cfg"]["h"]) for N in FIX_N}
    reuse = P["engine_version"] == MC.ENGINE_REUSE
    rd = os.path.join(root, "results", "eqb_gateway") if reuse else os.path.join(root, "results", "mechanism", exp, name)
    F["results_dir"] = rd
    F["out_dir"] = os.path.basename(rd)
    if reuse:        # run_ladder's ledger in the reused tree; the gate record of the fixture reuse files
        F["ledger"], F["ledger_filter"] = os.path.join(rd, "ledger.csv"), None
        F["reuse"] = dict(F["reuse"], source=rd, gate_record=os.path.join(root, "reuse_gate", "reuse_gate.json"),
                          gate_required_N=list(FIX_N), gate_min_jobs=2 * len(FIX_N))
    else:            # run_cells.py's layout: one ledger per experiment, rows filtered to the variant
        F["ledger"] = os.path.join(root, "results", "mechanism", exp, "ledger.csv")
        F["ledger_filter"] = dict(P["ledger_filter"])
    F["analysis_dir"] = os.path.join(root, "analysis", exp, name)
    F["fig_dir"] = os.path.join(root, "figures", exp, name)
    F["reference_file"] = os.path.join(root, "references", os.path.basename(P["reference_file"]))
    for N in FIX_N:
        assert (FIX_B // N) * N == FIX_B and (FIX_B // N) % 200 == 0
    return F


def run_one(args):
    """One (engine, N, seed, method) job; returns the ledger row."""
    engine, cfg, P_grid, N, seed, method, n_steps, path = args
    if engine == MC.ENGINE_REUSE:
        import gateway_ladder_numba as E
    else:
        import gateway_family_numba as E
    t0 = time.time()
    status = "complete"
    try:
        res = E.run_job(cfg, method, N, seed, n_steps, path, save_steps=RL.save_grid(P_grid, n_steps),
                        checkpoint_every_s=600.0)
        rec = dict(wall_s=float(res.get("wall_s", time.time() - t0)), peak_rss_mb=float(res.get("peak_rss_mb", float("nan"))),
                   n_force_evals=int(res.get("n_force_evals", -1)))
    except Exception as e:  # noqa: BLE001  (never mark a failed run complete)
        status = f"FAILED: {type(e).__name__}: {e}"
        rec = dict(wall_s=time.time() - t0, peak_rss_mb=float("nan"), n_force_evals=-1)
    return dict(N=N, seed=seed, method=method, n_steps=n_steps, status=status, **rec,
                finished_utc=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=DEFAULT_ROOT)
    ap.add_argument("--cells", nargs="*", default=None, help="EXPERIMENT/VARIANT (default: every cell)")
    ap.add_argument("--workers", type=int, default=8)
    ap.add_argument("--force", action="store_true", help="delete existing fixture runs first")
    a = ap.parse_args(argv)
    root = os.path.abspath(a.root)
    cells = MC.build_all()
    if a.cells:
        cells = {k: v for k, v in cells.items() if f"{k[0]}/{k[1]}" in a.cells}
    eqb = json.load(open(MC.EQB_GATEWAY))
    jobs, trees, cell_of = {}, {}, {}
    for (exp, name), P in cells.items():
        F = fixture_cell(P, root)
        p = os.path.join(root, "configs", "cells", exp, f"{name}.json")
        os.makedirs(os.path.dirname(p), exist_ok=True)
        with open(p, "w") as fh:
            json.dump(F, fh, indent=1)
        reuse = P["engine_version"] == MC.ENGINE_REUSE
        cfg = dict(eqb["engine_cfg"]) if reuse else dict(F["engine_cfg"])     # reuse: the equal-budget engine cfg
        grid_P = dict(F, system_key="gateway")
        rd = F["results_dir"]
        trees[rd] = F
        for N in FIX_N:
            n_steps = FIX_B // N
            for s in F["seeds"]:
                for m in ("abf", "fr"):
                    path = os.path.join(rd, f"N{N}", f"s{s}_{m}.npz")
                    if a.force and os.path.exists(path):
                        os.remove(path)
                    jobs[path] = (F["engine_version"], cfg, grid_P, N, int(s), m, n_steps, path)
                    cell_of[path] = F
        print(f"fixture cell {exp}/{name}: {p} -> {rd}", flush=True)
    from concurrent.futures import ProcessPoolExecutor, as_completed
    t0 = time.time()
    rows = {}
    with ProcessPoolExecutor(max_workers=a.workers) as ex:
        futs = {ex.submit(run_one, j): path for path, j in jobs.items()}
        for k, fu in enumerate(as_completed(futs)):
            r = fu.result()
            rows[futs[fu]] = r
            if r["status"] != "complete" or (k + 1) % 12 == 0:
                print(f"[{k + 1}/{len(jobs)}] {futs[fu]}: {r['status']} {r['wall_s']:.1f} s", flush=True)
    # ledgers in the production layout (the audit reads each cell's 'ledger' with its 'ledger_filter')
    ledgers = {}
    for path, r in sorted(rows.items()):
        F = cell_of[path]
        if F["engine_version"] == MC.ENGINE_REUSE:      # run_ladder.py's ledger of the reused tree
            ledgers.setdefault(F["ledger"], (LEDGER_FIELDS, []))[1].append(dict(system="gateway", **r))
        else:                                            # run_cells.py's ledger, one per experiment
            ledgers.setdefault(F["ledger"], (RC.LEDGER_FIELDS, []))[1].append(
                dict(experiment=F["experiment"], variant=F["cell"], **r))
    for lp, (fields, rws) in ledgers.items():
        os.makedirs(os.path.dirname(lp), exist_ok=True)
        old = []
        if os.path.exists(lp):                           # other cells of the experiment built earlier: keep their rows
            with open(lp, newline="") as fh:
                done = {(str(x["N"]), str(x["seed"]), x["method"], x.get("variant")) for x in rws}
                old = [x for x in csv.DictReader(fh)
                       if (str(x.get("N")), str(x.get("seed")), x.get("method"), x.get("variant")) not in done]
        with open(lp, "w", newline="") as fh:
            w = csv.DictWriter(fh, fieldnames=fields)
            w.writeheader()
            for x in old + rws:
                w.writerow({k: x.get(k) for k in fields})
    failed = [p for p, r in rows.items() if r["status"] != "complete"]
    print(f"{len(rows)} fixture jobs in {time.time() - t0:.1f} s; {len(failed)} failed {failed[:3]}", flush=True)
    # scripts/mechanism/build_references.py, loaded by path (scripts/equal_budget has a module of the same name)
    import importlib.util
    spec = importlib.util.spec_from_file_location("mech_build_references", os.path.join(HERE, "build_references.py"))
    BR = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(BR)
    rc = BR.main(["--cells-root", os.path.join(root, "configs", "cells")])
    # the bitwise-reuse gate on the fixture reuse tree (one record serves alpha1 and lam1, as in production)
    rg = 0
    reuse_cfgs = sorted(os.path.join(root, "configs", "cells", e, f"{n}.json") for (e, n), P in cells.items()
                        if P["engine_version"] == MC.ENGINE_REUSE)
    if reuse_cfgs and not failed:
        import reuse_gate as RG          # a regular import: its pool workers must be able to unpickle run_one
        rg = RG.main(["--cell", reuse_cfgs[0], "--workers", str(a.workers)])
    return 1 if (failed or rc or rg) else 0



if __name__ == "__main__":
    sys.exit(main())
