"""Regenerate docs/MANIFOLD_TABLES.md from stored results.

Same discipline as scripts/make_tables.py: no number in the manifold write-ups is
hand-transcribed.  Reads results/manifold/**.json only.
"""
import json, os, sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "results" / "manifold"
OUT = ROOT / "docs" / "MANIFOLD_TABLES.md"

ARM_LABEL = {
    "ti_cold": "fixed windows, cold fiber",
    "ti_warm": "fixed windows, equilibrium start",
    "fr_only": "birth-death only, no transport",
    "wfr_cart": "WFR, cartesian lift",
    "wfr_minnorm": "WFR, minimum-norm lift",
    "wfr_fit": "WFR, self-built lift (running average)",
    "wfr_fit_decay": "WFR, self-built lift (with forgetting)",
    "wfr_adiab": "WFR, adiabatic lift",
    "wfr_oracle": "WFR, oracle conditional refresh",
}
ORDER = list(ARM_LABEL)


def q(v, p):
    return float(np.percentile(np.asarray(v, float), p))


def arms_block(path: Path) -> str:
    d = json.load(open(path))
    fl, arms = d["floor"], d["arms"]
    base = np.median(arms["wfr_cart"]["final"]) if "wfr_cart" in arms else None
    cols = ["arm", "median e_F", "IQR", "/ floor"]
    if base:
        cols.append("vs cartesian")
    has_dz = any("dcond_z" in v for v in arms.values())
    cols += ["D_pool"] + (["D_z"] if has_dz else [])
    L = ["| " + " | ".join(cols) + " |",
         "|" + "|".join(["---"] * len(cols)) + "|"]
    for a in ORDER:
        if a not in arms:
            continue
        v = arms[a]
        m = float(np.median(v["final"]))
        row = [ARM_LABEL[a], f"{m:.4f}",
               f"[{q(v['final'],25):.4f}, {q(v['final'],75):.4f}]", f"{m/fl:.1f}"]
        if base:
            row.append("--" if a == "wfr_cart" else f"{100*(m-base)/base:+.1f}%")
        row.append(f"{v['dcond'][-1]:+.4f}")
        if has_dz:
            row.append(f"{v['dcond_z'][-1]:.4f}" if "dcond_z" in v else "--")
        L.append("| " + " | ".join(row) + " |")
    return "\n".join(L) + f"\n\nEstimator floor {fl:.5f}.\n"


def main():
    parts = ["# Manifold-phase tables",
             "",
             "Machine-generated by `scripts/make_manifold_tables.py` from",
             "`results/manifold/`. Do not edit by hand.", ""]

    # ---- arm comparisons ---------------------------------------------------
    for p in sorted((RES / "arms").glob("*.json")):
        name = p.stem
        parts += [f"## Arms: `{name}`", "", arms_block(p), ""]

    # ---- lift lag ----------------------------------------------------------
    for p in sorted(RES.glob("lift_a_*.json")):
        d = json.load(open(p))
        parts += [f"## Lift lag: a = {d['a']}, k = {d['k']}", "",
                  "| z0 | C cartesian | C min-norm | ratio | "
                  "measured/predicted at dz = 0.0125 |", "|---|---|---|---|---|"]
        for z0 in sorted(set(r["z0"] for r in d["rows"])):
            rs = [r for r in d["rows"] if r["z0"] == z0]
            C = rs[0]["C"]
            fine = min(rs, key=lambda r: r["dz"])
            ratio = fine["kl_cartesian"] / max(fine["pred_cartesian"], 1e-30)
            parts.append(f"| {z0:+.2f} | {C['cartesian']:.2f} | {C['minnorm']:.2f} | "
                         f"{C['minnorm']/C['cartesian']:.3f} | {ratio:.3f} |")
        adia = max(abs(r["klmc_adiabatic"]) for r in d["rows"])
        parts += ["", f"Adiabatic lift: max |PIT-KL| over all (z0, dz) = {adia:.2e}.", ""]

    # ---- timescale ---------------------------------------------------------
    ts = RES / "timescale.json"
    if ts.exists():
        rows = [r for r in json.load(open(ts))["rows"] if r["v"] > 0]
        well = [r for r in rows if -1.15 < r["z"] < -0.55]
        parts += ["## Timescale law (left well, linear-response regime)", "",
                  "| omega | v | lift | measured | predicted | ratio |",
                  "|---|---|---|---|---|---|"]
        rat = {"cartesian": [], "minnorm": []}
        for om in sorted(set(r["omega"] for r in well)):
            for v in sorted(set(r["v"] for r in well)):
                sub = [r for r in well if r["omega"] == om and r["v"] == v]
                for m in ("cartesian", "minnorm"):
                    if not sub:
                        continue
                    me = float(np.mean([r["D_" + m] for r in sub]))
                    pr = float(np.mean([r["pred_" + m] for r in sub]))
                    if not (3e-4 < pr < 0.1):
                        continue
                    rat[m].append(me / pr)
                    parts.append(f"| {om:.2f} | {v:.3f} | {m} | {me:.5f} | "
                                 f"{pr:.5f} | {me/pr:.2f} |")
        parts.append("")
        for m, rr in rat.items():
            if rr:
                parts.append(f"* {m}: n = {len(rr)}, median ratio "
                             f"{np.median(rr):.2f} [{min(rr):.2f}, {max(rr):.2f}]")
        ad = [r["D_adiabatic"] for r in rows]
        parts += ["", f"* adiabatic lift over ALL (z, v, omega): median "
                      f"{np.median(ad):.2e}, max {max(ad):.2e} (cartesian max "
                      f"{max(r['D_cartesian'] for r in rows):.2f})", ""]

    # ---- Fixman ------------------------------------------------------------
    fx = RES / "fixman.json"
    if fx.exists():
        d = json.load(open(fx))
        parts += ["## Fixman / rigid gap (exact quadrature)", "",
                  "| a k | RMSE(F - F_rgd), max over systems | multiple of floor |",
                  "|---|---|---|"]
        for ak in sorted(set(round(r["ak"], 3) for r in d["rows"] if r["a"] > 0)):
            sub = [r for r in d["rows"] if round(r["ak"], 3) == ak]
            m = max(r["rmse_F_minus_Frgd"] for r in sub)
            parts.append(f"| {ak:.2f} | {m:.5f} | {m/d['floor']:.1f} |")
        parts.append("")

    # ---- estimator variance ------------------------------------------------
    ev = RES / "estimator_variance.json"
    if ev.exists():
        rows = json.load(open(ev))
        g = [r["gain_vs_best"] for r in rows]
        rr = [r["ratio_lrs_graph"] for r in rows]
        cc = [r["corr"] for r in rows]
        parts += ["## Mean-force control variate", "",
                  f"* Var(f_LRS)/Var(f_graph) over {len(rows)} (system, a, k, z) points: "
                  f"{min(rr):.3f} to {max(rr):.1f} -- neither estimator dominates",
                  f"* variance gain of the optimal combination over the better single "
                  f"estimator: median {np.median(g):.2f}x, max {max(g):.1f}x",
                  f"* correlation between the two estimators: median {np.median(cc):.5f}, "
                  f"max {max(cc):.6f}", ""]

    # ---- tau_eff vs the spectral-gap time ---------------------------------
    try:
        sys.path.insert(0, str(ROOT / "src"))
        import torch
        from rcwfr.systems.graph import build_mfib, lag_coefficients
        parts += ["## Timescale: tau_eff against the spectral-gap time", "",
                  "MFIB, a = 0.6, k = 0.7, z = -0.9. `tau_eff = sqrt(C_eff / C)` is the",
                  "fiber relaxation time WEIGHTED BY WHERE THE LIFT ERROR LIVES; the",
                  "spectral-gap time `1/omega^2` is what the proposal names instead.", "",
                  "| omega | 1/omega^2 | tau_eff (cartesian) | over-estimate | "
                  "in D_cond |", "|---|---|---|---|---|"]
        for om in (0.85, 1.0, 1.4, 2.0, 2.8):
            s = build_mfib(omega=om, a=0.6, k=0.7)
            te = lag_coefficients(s, -0.9, "cartesian")["tau_eff"]
            r = (1.0 / om ** 2) / te
            parts.append(f"| {om:.2f} | {1/om**2:.3f} | {te:.3f} | {r:.1f}x | "
                         f"{r*r:.0f}x |")
            del s
            torch.cuda.empty_cache()
        parts.append("")
    except Exception as e:                       # table generation must not be fatal
        parts += [f"(tau_eff table unavailable: {e})", ""]

    OUT.write_text("\n".join(parts) + "\n")
    print(f"wrote {OUT} ({len(parts)} blocks)")


if __name__ == "__main__":
    main()
