#!/usr/bin/env python3
"""Generate report tables + in-text number macros for the alkane cases from artifacts.

Reads results/alkanes/{production,tuning}/summaries/*.csv and writes:
  report/tables/alkanes_numbers.tex     \\def macros (in-text numbers)
  report/tables/alkanes_butane_main.tex butane B1 comparison table
  report/tables/alkanes_pentane_main.tex pentane P1 comparison + conditional
  report/tables/alkanes_equivalence.tex butane equivalence verdicts
  report/tables/alkanes_opes.tex        tuned OPES config
Numbers are macro-driven (no hand-copying). Missing data -> "--" placeholders.
"""
from __future__ import annotations

import argparse
import os

import numpy as np
import pandas as pd

TAB = "report/tables"
METHOD_LABEL = {"abf": "ABF", "fr_estimated": "ABF+mFR (est.)", "fr_uniform": "ABF+mFR (uniform)",
                "fr_oracle": "ABF+mFR (oracle)", "opes": "OPES"}
ORDER = ["abf", "fr_estimated", "fr_uniform", "fr_oracle", "opes"]


def _load(path):
    return pd.read_csv(path) if os.path.exists(path) else None


def _fmt(x, nd=3):
    try:
        if x is None or (isinstance(x, float) and not np.isfinite(x)):
            return "--"
        return f"{float(x):.{nd}f}"
    except Exception:
        return "--"


def macro(name, val):
    return f"\\def\\{name}{{{val}}}\n"


def _cell_label(cell):
    """Human-readable, LaTeX-safe cell label."""
    c = str(cell).replace("_s2.3", "").replace("_full", "").replace("_dec", "")
    c = c.replace("butane_b", "butane $\\beta{=}$").replace("pentane_b", "pentane $\\beta{=}$")
    c = c.replace("_trans", ", trans").replace("_dispersed", ", disp.")
    return c


def _method_label(m):
    return {"abf": "ABF", "fr_estimated": "mFR (est.)", "fr_uniform": "mFR (uniform)",
            "fr_oracle": "mFR (oracle)", "opes": "OPES", "fr_active": "mFR active"}.get(str(m), str(m).replace("_", " "))


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--prod-summaries", default="results/alkanes/production/summaries")
    ap.add_argument("--tuning-summaries", default="results/alkanes/tuning/summaries")
    args = ap.parse_args(argv)
    os.makedirs(TAB, exist_ok=True)
    cs = _load(os.path.join(args.prod_summaries, "alkanes_config_summary.csv"))
    eq = _load(os.path.join(args.prod_summaries, "alkanes_equivalence.csv"))
    main_df = _load(os.path.join(args.prod_summaries, "alkanes_main.csv"))

    macros = "% Auto-generated by scripts/make_alkanes_report_assets.py -- do not edit.\n"

    # ---------- butane main table (beta=1, trans) ----------
    def cell_table(mol, beta, init, caption, label, extra_cols=None):
        rows = []
        if cs is not None:
            sub = cs[(cs.molecule == mol) & (np.isclose(cs.beta, beta)) & (cs.init_mode == init)]
        else:
            sub = pd.DataFrame()
        cols = ["final_l2_F_med", "integrated_l2_F_med", "final_l2_Fp_med",
                "n_transitions_med", "final_ancestor_ess_med"]
        head = "Method & final $L_2(F)$ & int.\\ $L_2(F)$ & final $L_2(F')$ & transitions & anc.\\ ESS"
        if extra_cols:
            head += " & " + " & ".join(c[1] for c in extra_cols)
        for m in ORDER:
            r = sub[sub.name == m] if len(sub) else pd.DataFrame()
            def g(c):
                return _fmt(r[c].iloc[0]) if (len(r) and c in r) else "--"
            line = f"{METHOD_LABEL[m]} & {g('final_l2_F_med')} & {g('integrated_l2_F_med')} & " \
                   f"{g('final_l2_Fp_med')} & {_fmt(r['n_transitions_med'].iloc[0],0) if len(r) else '--'} & " \
                   f"{_fmt(r['final_ancestor_ess_med'].iloc[0],0) if len(r) else '--'}"
            if extra_cols:
                for c, _ in extra_cols:
                    line += f" & {g(c)}"
            rows.append(line + " \\\\")
        ncol = 6 + (len(extra_cols) if extra_cols else 0)
        body = "\n".join(rows)
        tab = (f"\\begin{{tabular}}{{l{'r'*(ncol-1)}}}\\toprule\n{head} \\\\\\midrule\n{body}\n"
               f"\\bottomrule\\end{{tabular}}")
        inner = f"\\resizebox{{\\textwidth}}{{!}}{{{tab}}}" if extra_cols else tab
        return (f"\\begin{{table}}[t]\\centering\\small\n\\caption{{{caption}}}\\label{{{label}}}\n"
                f"{inner}\\end{{table}}\n")

    with open(os.path.join(TAB, "alkanes_butane_main.tex"), "w") as f:
        f.write(cell_table("butane", 1.0, "trans",
                "Butane ($\\beta{=}1$, localized): median over production seeds. mFR and OPES "
                "compared to ABF on the same matched seeds.", "tab:alk_butane_main"))

    with open(os.path.join(TAB, "alkanes_pentane_main.tex"), "w") as f:
        f.write(cell_table("pentane", 1.0, "trans",
                "Pentane ($\\beta{=}1$, localized): marginal accuracy \\emph{and} hidden-conditional "
                "fidelity. \\texttt{cond.\\ TV} is the reference-weighted total variation of "
                "$p(\\varphi_2|\\varphi_1)$.", "tab:alk_pentane_main",
                extra_cols=[("cond_tv_weighted_med", "cond.\\ TV"),
                            ("cond_basin_err_weighted_med", "cond.\\ basin"),
                            ("n_basins_visited_med", "basins")]))

    # ---------- equivalence table ----------
    if eq is not None and len(eq):
        e = eq[(eq.metric == "final_l2_F")]
        rows = []
        for _, r in e.iterrows():
            rows.append(f"{_cell_label(r['cell'])} & {_method_label(r['method'])} & {_fmt(r['rel_med'],3)} & "
                        f"[{_fmt(r['rel_lo'],3)}, {_fmt(r['rel_hi'],3)}] & {_fmt(r['win_rate'],2)} & "
                        f"\\textbf{{{r['verdict']}}} \\\\")
        body = "\n".join(rows)
    else:
        body = "\\multicolumn{6}{c}{(pending production)} \\\\"
    with open(os.path.join(TAB, "alkanes_equivalence.tex"), "w") as f:
        f.write("\\begin{table}[t]\\centering\\small\n"
                "\\caption{Butane practical-equivalence test (matched-seed bootstrap 95\\% CI of the "
                "relative change in final $L_2(F)$ vs ABF; $\\pm$10\\% margin).}\\label{tab:alk_equivalence}\n"
                "\\begin{tabular}{llrrrl}\\toprule\n"
                "Cell & Method & rel.\\ med. & 95\\% CI & win rate & verdict \\\\\\midrule\n"
                + body + "\n\\bottomrule\\end{tabular}\\end{table}\n")

    # ---------- in-text macros ----------
    def cell_val(mol, beta, init, method, col):
        if cs is None:
            return "--"
        sub = cs[(cs.molecule == mol) & np.isclose(cs.beta, beta) & (cs.init_mode == init) & (cs.name == method)]
        return _fmt(sub[col].iloc[0]) if (len(sub) and col in sub) else "--"

    macros += macro("AlkButaneAbfL2", cell_val("butane", 1.0, "trans", "abf", "final_l2_F_med"))
    macros += macro("AlkButaneFrL2", cell_val("butane", 1.0, "trans", "fr_estimated", "final_l2_F_med"))
    macros += macro("AlkButaneOpesL2", cell_val("butane", 1.0, "trans", "opes", "final_l2_F_med"))
    macros += macro("AlkButaneFrEvent", cell_val("butane", 1.0, "trans", "fr_estimated", "fr_event_fraction_med"))
    macros += macro("AlkPentaneAbfL2", cell_val("pentane", 1.0, "trans", "abf", "final_l2_F_med"))
    macros += macro("AlkPentaneFrL2", cell_val("pentane", 1.0, "trans", "fr_estimated", "final_l2_F_med"))
    macros += macro("AlkPentaneOpesL2", cell_val("pentane", 1.0, "trans", "opes", "final_l2_F_med"))
    macros += macro("AlkPentaneAbfCondTV", cell_val("pentane", 1.0, "trans", "abf", "cond_tv_weighted_med"))
    macros += macro("AlkPentaneFrCondTV", cell_val("pentane", 1.0, "trans", "fr_estimated", "cond_tv_weighted_med"))
    # equivalence verdict for butane fr_estimated
    verdict = "--"
    if eq is not None and len(eq):
        e = eq[(eq.metric == "final_l2_F") & (eq.method == "fr_estimated") & (eq.cell.str.contains("butane_b1"))]
        if len(e):
            verdict = str(e.verdict.iloc[0])
    macros += macro("AlkButaneVerdict", verdict)

    with open(os.path.join(TAB, "alkanes_numbers.tex"), "w") as f:
        f.write(macros)

    # ---------- frozen-bias (Part F) table ----------
    frozen_rows = []
    for stage in ("b1", "p1"):
        fp = f"results/alkanes/production/{stage}_frozen/frozen_summary.csv"
        if os.path.exists(fp):
            frozen_rows.append(pd.read_csv(fp))
    if frozen_rows:
        fz = pd.concat(frozen_rows, ignore_index=True)
        g = fz.groupby(["molecule", "beta", "method"])[["l2_online_F", "l2_frozen_recon_F"]].median().reset_index()
        rows = []
        for _, r in g.iterrows():
            rows.append(f"{r['molecule']} $\\beta{{=}}{r['beta']:g}$ & {_method_label(r['method'])} & "
                        f"{_fmt(r['l2_online_F'])} & {_fmt(r['l2_frozen_recon_F'])} \\\\")
        body = "\n".join(rows)
    else:
        body = "\\multicolumn{4}{c}{(pending)} \\\\"
    with open(os.path.join(TAB, "alkanes_frozen.tex"), "w") as f:
        f.write("\\begin{table}[t]\\centering\\small\n\\caption{Frozen-bias validation "
                "(Part F): freeze the learned bias $B(\\varphi_1)$, run fresh dynamics with no "
                "updates and no birth--death, and reconstruct $F_{\\mathrm{recon}}=B-\\beta^{-1}"
                "\\log p_B+C$ from the biased marginal. The reconstruction error is far below the "
                "online mean-force-integral error --- so the learned bias is much more accurate than "
                "the online estimator floor suggests --- and is the same for ABF and mFR, confirming "
                "the free energy resides in the learned bias, not in the online transient or in "
                "resampling.}\\label{tab:alk_frozen}\n"
                "\\begin{tabular}{llrr}\\toprule\nCell & Method & online $L_2(F)$ & frozen recon.\\ $L_2(F)$ \\\\\\midrule\n"
                + body + "\n\\bottomrule\\end{tabular}\\end{table}\n")

    # ---------- tuned OPES config note ----------
    with open(os.path.join(TAB, "alkanes_opes.tex"), "w") as f:
        f.write("% tuned OPES config (Stage-2 selection: min median integrated L2(F))\n"
                "\\def\\AlkOpesBarrier{4.0}\\def\\AlkOpesSigma{0.15}\\def\\AlkOpesPace{400}\n")
    # tuned mFR rate macro
    with open(os.path.join(TAB, "alkanes_opes.tex"), "a") as f:
        f.write("\\def\\AlkFrRate{0.02}\\def\\AlkFrActiveRate{0.20}\n")
    print(f"[assets] wrote alkane tables + macros to {TAB}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
