#!/usr/bin/env python3
"""Generate LaTeX macros for the convergence-speed section (prefix ``Cv``).

Writes ``report/tables/convergence_numbers.tex`` from the atlas artifacts:

  results/convergence_atlas/speedup.json     per-panel endpoints and tau_eps speedups
  results/convergence_atlas/controls.json    frozen-bias rescore + EB target ablation

Every macro emits ``--`` when its input is absent, so the report ALWAYS compiles.

Usage:
  python scripts/extract_convergence_atlas.py
  python scripts/analyze_convergence_atlas.py
  python scripts/audit_convergence_controls.py
  python scripts/make_convergence_report_assets.py
"""
from __future__ import annotations

import json
import os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
ATLAS = os.path.join(ROOT, "results", "convergence_atlas")
OUT = os.path.join(ROOT, "report", "tables", "convergence_numbers.tex")

# panel -> macro infix. Only panels the section actually quotes.
PANELS = {
    "eb_beta8": "EbEight", "eb_beta12": "EbTwelve", "eb_beta4": "EbFour",
    "eb_beta2": "EbTwo", "wca_starved": "Wca", "wca_five_arm": "Five",
    "gateway_left": "Gw", "toy2d": "Toy", "butane_phi1": "But",
    "pentane_phi1": "Pen", "pentane_r15": "RFifteen", "alanine": "Ala",
}


def load(name):
    p = os.path.join(ATLAS, name)
    return json.load(open(p)) if os.path.exists(p) else None


def fmt(x, nd=2, pct=True):
    if x is None:
        return "--"
    try:
        v = float(x)
    except (TypeError, ValueError):
        return "--"
    if v != v:                                   # NaN
        return "--"
    return f"{v:+.{nd}f}" if pct else f"{v:.{nd}f}"


def main():
    spd, ctl = load("speedup.json"), load("controls.json")
    L = ["% Auto-generated by scripts/make_convergence_report_assets.py -- do not edit.",
         "% Source: results/convergence_atlas/{speedup,controls}.json",
         ""]

    def cmd(name, value):
        L.append(f"\\newcommand{{\\Cv{name}}}{{{value}}}")

    # ---- per-panel: integrated endpoint, CI, wins, final endpoint, speedup ----
    n_fast = n_same = n_slow = 0
    for panel, tag in PANELS.items():
        rec = (spd or {}).get("panels", {}).get(panel)
        e = (rec or {}).get("arms", {}).get("mfr") or (rec or {}).get("arms", {}).get("mfr_oracle")
        if not e:
            for suf in ("Int", "CIlo", "CIhi", "Wins", "Seeds", "Final", "Speedup"):
                cmd(tag + suf, "--")
            continue
        m, (lo, hi) = e["rel_integrated_pct"], e["rel_integrated_ci95"]
        cmd(tag + "Int", fmt(m))
        cmd(tag + "CIlo", fmt(lo))
        cmd(tag + "CIhi", fmt(hi))
        cmd(tag + "Wins", str(e["wins"]))
        cmd(tag + "Seeds", str(e["n_paired"]))
        cmd(tag + "Final", fmt(e["rel_final_pct"]))
        sp = e["speedup"]["abf_final"]
        cmd(tag + "Speedup", f"{sp['median_curve']:.1f}" if sp["status"] == "ok" else "--")
        # the regime tally quoted in the abstract, counted here rather than by hand
        if panel not in ("wca_five_arm", "gateway_one_right", "pentane_2d"):
            if m <= -5.0 and hi < 0:
                n_fast += 1
            elif m >= +5.0 and lo > 0:
                n_slow += 1
            else:
                n_same += 1
    cmd("NFaster", str(n_fast) if spd else "--")
    cmd("NSame", str(n_same) if spd else "--")
    cmd("NSlower", str(n_slow) if spd else "--")
    cmd("NCells", str(n_fast + n_same + n_slow) if spd else "--")

    # ---- five-arm comparator, the one that decides FR-specificity ----
    fa = (spd or {}).get("panels", {}).get("wca_five_arm", {}).get("arms", {})
    cmd("FiveCount", fmt(fa.get("count_balancing", {}).get("rel_integrated_pct")))
    cmd("FiveBook", fmt(fa.get("book_laplacian", {}).get("rel_integrated_pct")))

    # ---- frozen-bias rescore against the corrected reference ----
    fb = (ctl or {}).get("frozen_bias_wca", {})
    k = "b1_h2::fr_estimated::corrected_ref"
    cmd("WcaFrozen", fmt(fb.get(k, {}).get("median_pct")))
    cmd("WcaFrozenWins", str(fb[k]["wins"]) if k in fb else "--")
    cmd("WcaFrozenSeeds", str(fb[k]["n"]) if k in fb else "--")
    cmd("WcaFrozenAbf", fmt(fb.get(k, {}).get("abf_median"), nd=4, pct=False))
    cmd("WcaFrozenFr", fmt(fb.get(k, {}).get("arm_median"), nd=4, pct=False))
    ko = "b1_h2::fr_estimated::stored_superseded_ref"
    cmd("WcaFrozenOld", fmt(fb.get(ko, {}).get("median_pct")))

    # ---- entropic-bottleneck target ablation and dose response ----
    eb = (ctl or {}).get("entropic_bottleneck", {})
    ta = eb.get("target_ablation_beta8", {})
    for arm, tag in (("fr_estimated", "AblEst"), ("fr_uniform", "AblUni"), ("fr_oracle", "AblOra")):
        cmd(tag, fmt(ta.get(arm, {}).get("median_pct")))
        cmd(tag + "Wins", str(ta[arm]["wins"]) if arm in ta else "--")
        cmd(tag + "Seeds", str(ta[arm]["n"]) if arm in ta else "--")
    dose = eb.get("gamma_dose_response_beta8", {})
    for g, tag in (("gamma1", "One"), ("gamma3", "Three"), ("gamma5", "Five"),
                   ("gamma10", "Ten"), ("gamma15", "Fifteen"),
                   ("gamma25", "TwentyFive"), ("gamma50", "Fifty")):
        cmd("Dose" + tag, fmt(dose.get(g, {}).get("median_pct")))

    # ---- method parameters, so the section never states them by hand ----
    meth = (spd or {}).get("method", {})
    cmd("Persist", f"{meth.get('persistence_fraction', float('nan')):.1f}" if meth else "--")

    with open(OUT, "w") as fh:
        fh.write("\n".join(L) + "\n")
    print(f"wrote {os.path.relpath(OUT, ROOT)}  ({len(L) - 3} macros)")
    if spd:
        print(f"  regime tally: {n_fast} faster / {n_same} no difference / {n_slow} slower")


if __name__ == "__main__":
    main()
