#!/usr/bin/env python
"""Emit report/tables/opes_closure_numbers.tex (prefix OPESClo) from the closure
study outputs. Auto-generated macros; mirrors make_opes_report_assets.py style.

Sources (defaults):
  results/opes_closure/wca/metrics/production_method_comparison.json
  results/opes_closure/wca/metrics/freeze_tune_r3_to_production.json
  results/opes_closure/{eb,meta}/metrics/per_config.csv
"""
import argparse
import csv
import json
import os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
OUT = os.path.join(ROOT, "report", "tables", "opes_closure_numbers.tex")

# production_method_comparison.json keys -> report tag
WCA_CELLS = {"b1_h2 STARVED": "Starved", "b2_h6 INTERMEDIATE": "Inter",
             "b4_h1 EASY": "Easy"}
# freeze winners keys -> report tag
WCA_FREEZE = {"b1_h2": "Starved", "b2_h6": "Inter", "b4_h1": "Easy"}
METHODS = {"opes": "Adapt", "opes_fixedg": "Fixedg", "opes_flat": "Flat"}


def cmd(name, val):
    return f"\\def\\{name}{{{val}}}"


def _fmt(val, nd=4):
    try:
        v = float(val)
        return f"{v:.{nd}f}" if abs(v) < 100 else f"{v:.0f}"
    except Exception:
        return "--"


def _read_csv(path):
    if not os.path.exists(path):
        return []
    return list(csv.DictReader(open(path)))


def _load_json(path):
    return json.load(open(path)) if os.path.exists(path) else {}


def _g(val, nd=3):
    try:
        return f"{float(val):g}"
    except Exception:
        return "--"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--wca-comparison",
                    default="results/opes_closure/wca/metrics/production_method_comparison.json")
    ap.add_argument("--wca-freeze",
                    default="results/opes_closure/wca/metrics/freeze_tune_r3_to_production.json")
    ap.add_argument("--eb-per-config",
                    default="results/opes_closure/eb/metrics/per_config.csv")
    ap.add_argument("--meta-per-config",
                    default="results/opes_closure/meta/metrics/per_config.csv")
    args = ap.parse_args(argv)

    lines = [r"% Auto-generated by make_opes_closure_assets.py. Do not edit by hand.",
             r"% OPES closure-study macros (prefix OPESClo)."]

    # ---- WCA: 3 cells x 3 methods (adaptive / fixed-gamma / flat) ----
    comp = _load_json(os.path.join(ROOT, args.wca_comparison))
    for ckey, ctag in WCA_CELLS.items():
        cell = comp.get(ckey, {})
        for mkey, mtag in METHODS.items():
            m = cell.get(mkey, {})
            lines.append(cmd(f"OPESClo{ctag}{mtag}LtwoF", _fmt(m.get("l2f"))))
            lines.append(cmd(f"OPESClo{ctag}{mtag}CI", _fmt(m.get("ci95"))))
        # per-cell best (adaptive) neff for context
        lines.append(cmd(f"OPESClo{ctag}NeffMin",
                         _fmt(cell.get("opes", {}).get("neff_min"))))

    # ---- WCA frozen winners per cell (barrier / pace / sigma) ----
    frz = _load_json(os.path.join(ROOT, args.wca_freeze))
    winners = frz.get("winners", {})
    for wkey, wtag in WCA_FREEZE.items():
        w = winners.get(wkey, {})
        lines.append(cmd(f"OPESClo{wtag}Barrier", _g(w.get("opes_barrier"))))
        lines.append(cmd(f"OPESClo{wtag}Pace", _g(w.get("opes_pace"))))
        lines.append(cmd(f"OPESClo{wtag}Sigma", _g(w.get("opes_sigma"))))
    lines.append(cmd("OPESCloWCASteps", _g(frz.get("n_steps"))))
    lines.append(cmd("OPESCloWCANSeeds", str(len(frz.get("seeds", [])) or "--")))

    # ---- toys: tuned representative + matched pilot-sigma reference ----
    for toy, per_cfg, tag in [("eb", args.eb_per_config, "EB"),
                              ("meta", args.meta_per_config, "Meta")]:
        rows = _read_csv(os.path.join(ROOT, per_cfg))
        by_stage = {r["stage"]: r for r in rows}
        rep = by_stage.get("representative")
        if rep:
            lines.append(cmd(f"OPESClo{tag}TunedLtwoF", _fmt(rep["l2_f_common_mean"])))
            lines.append(cmd(f"OPESClo{tag}TunedCI", _fmt(rep["l2_f_common_ci95"])))
            lines.append(cmd(f"OPESClo{tag}TunedSigma", _g(rep["opes_sigma"])))
            lines.append(cmd(f"OPESClo{tag}TunedBarrier", _g(rep["opes_barrier"])))
            lines.append(cmd(f"OPESClo{tag}TunedPace", _g(rep["opes_pace"])))
        ref = by_stage.get("pilot_sigma_ref")
        if ref:
            lines.append(cmd(f"OPESClo{tag}PilotLtwoF", _fmt(ref["l2_f_common_mean"])))
            lines.append(cmd(f"OPESClo{tag}PilotCI", _fmt(ref["l2_f_common_ci95"])))
            lines.append(cmd(f"OPESClo{tag}PilotSigma", _g(ref["opes_sigma"])))
            # matched-sigma improvement factor + pct
            try:
                t = float(rep["l2_f_common_mean"]); p = float(ref["l2_f_common_mean"])
                lines.append(cmd(f"OPESClo{tag}SigmaFactor", f"{p/t:.2f}"))
                lines.append(cmd(f"OPESClo{tag}SigmaPct", f"{(1-t/p)*100:.0f}"))
            except Exception:
                pass

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"[write] {OUT}  ({len(lines)-2} macros)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
