#!/usr/bin/env python3
"""Generate report tables + in-text number macros for the CV-extension sections.

Reads results/alkanes_cv_extension/{r15,r14,2d}/summaries/*.csv, the decoupled-gate and
reference validation JSONs, and writes:
  report/tables/cv_numbers.tex        \\def macros (in-text numbers; missing -> "--")
  report/tables/cv_r15_screen.tex     R15 (+R14) ABF starvation cells
  report/tables/cv_2d_validation.tex  2-D ABF validation tolerances (decoupled gate + refs)
  report/tables/cv_2d_screen.tex      2-D ABF starvation cells
  report/tables/cv_2d_methods.tex     2-D production method comparison (if run)
  report/tables/cv_starvation_map.tex cross-case starvation synthesis (phi1 / R15 / 2-D)
All numbers are macro-driven (no hand-copying).
"""
from __future__ import annotations

import argparse
import json
import os

import numpy as np
import pandas as pd

TAB = "report/tables"
ROOT = "results/alkanes_cv_extension"


def _load(path):
    return pd.read_csv(path) if os.path.exists(path) else None


def _fmt(x, nd=3):
    try:
        if x is None or (isinstance(x, float) and not np.isfinite(x)):
            return "--"
        return f"{float(x):.{nd}f}"
    except Exception:
        return "--"


def macro(name, val):
    return f"\\def\\{name}{{{val}}}\n"


def _cell_label(cell):
    import re
    c = str(cell)
    c = re.sub(r"^(screen|resgate|production|control|tuning|confirm)_", "", c)   # strip stage prefix
    c = re.sub(r"_g\d+$", "", c)                                                 # strip grid suffix
    c = c.replace("dist_pentane_", "R15 ").replace("dist_butane_", "R14 ")
    c = c.replace("joint2d_pentane_", "2D ")
    c = c.replace("b1", "$\\beta{=}1$").replace("b2", "$\\beta{=}2$").replace("b3", "$\\beta{=}3$")
    c = c.replace("_trans", " TT").replace("_dispersed", " disp").replace("_compact", " comp")
    return c


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=ROOT)
    args = ap.parse_args(argv)
    os.makedirs(TAB, exist_ok=True)
    macros = "% Auto-generated by scripts/make_alkanes_cv_report_assets.py -- do not edit.\n"
    # safe defaults so every macro used in the tables/text is defined even pre-results
    for nm in ("CvGateGridFine", "CvGateLtwo", "CvGateLtwoCoarse", "CvGateGridCoarse", "CvGateCondMax",
               "CvGateReg", "CvTwoDGateExact", "CvRfifteenStarv", "CvRfourteenStarv", "CvTwoDStarv",
               "CvTwoDStarvPrimary", "CvRfifteenEss", "CvRfifteenCross", "CvRfifteenRange", "CvTwoDmFRVerdict",
               "CvTwoDmFRRelFinal", "CvRfifteenLtwo", "CvTwoDAbfLtwo", "CvTwoDBasins",
               "CvRfifteenmFRVerdict", "CvRfifteenmFRRelFinal", "CvRfifteenmFRWin"):
        macros += macro(nm, "--")

    # ---------------- decoupled 2-D gate ----------------
    gate = os.path.join(args.root, "validation", "decoupled_2d_gate.json")
    gate_best = None
    if os.path.exists(gate):
        gj = json.load(open(gate))
        if gj["gate"]:
            fin = gj["gate"][-1]
            gate_best = fin["l2_thermal_median"]
            macros += macro("CvGateGridFine", fin["n_grid"])
            macros += macro("CvGateLtwo", _fmt(gate_best, 3))
            macros += macro("CvGateLtwoCoarse", _fmt(gj["gate"][0]["l2_thermal_median"], 3))
            macros += macro("CvGateGridCoarse", gj["gate"][0]["n_grid"])
            macros += macro("CvGateCondMax", _fmt(fin.get("gram_cond_max"), 1))
            macros += macro("CvGateReg", int(fin.get("gram_reg_activations", 0)))

    # ---------------- reference validation ----------------
    refj = os.path.join(args.root, "references", "cv_reference_validation.json")
    if os.path.exists(refj):
        rj = json.load(open(refj))
        for e in rj.get("dist", []):
            if e["cv"] == "pentane_R04" and abs(e["beta"] - 1.0) < 1e-6:
                macros += macro("CvRfifteenEss", _fmt(e.get("ess_frac_v4"), 2))
                macros += macro("CvRfifteenCross", _fmt(e.get("crosscheck_l2_thermal"), 3))
                macros += macro("CvRfifteenRange", _fmt(e.get("F_range_thermal_kT"), 1))
        for e in rj.get("joint2d", []):
            if abs(e["beta"] - 1.0) < 1e-6:
                macros += macro("CvTwoDGateExact", f"{e['decoupled_gate_max_abs_err']:.1e}")

    # ---------------- starvation verdicts ----------------
    def load_starv(sub):
        return _load(os.path.join(args.root, sub, "summaries", "cv_starvation.csv"))

    r15s = load_starv("r15"); twods = load_starv("2d"); r14s = load_starv("r14")

    def verdict_of(df, contains):
        if df is None:
            return "--"
        m = df[df.cell.str.contains(contains, regex=False)]
        if m.empty:
            return "--"
        # worst (most starved) verdict among matching cells
        order = {"easy": 0, "intermediate": 1, "starved": 2}
        return max(m.verdict, key=lambda v: order.get(v, 0))

    macros += macro("CvRfifteenStarv", verdict_of(r15s, "dist_pentane"))
    macros += macro("CvRfourteenStarv", verdict_of(r14s, "dist_butane"))
    macros += macro("CvTwoDStarv", verdict_of(twods, "joint2d_pentane"))
    macros += macro("CvTwoDStarvPrimary", verdict_of(twods, "joint2d_pentane_b2_trans"))

    # ---------------- mFR success verdict (2-D methods) ----------------
    succ = _load(os.path.join(args.root, "2d_methods", "summaries", "cv_success.csv"))
    if succ is not None and not succ.empty:
        # the manuscript quotes the PRIMARY (production) cell, not the easy control
        prim = succ[succ.cell.astype(str).str.startswith("production")]
        est = (prim if not prim.empty else succ)
        est = est[est.method.astype(str) == "fr_estimated"]
        if not est.empty:
            macros += macro("CvTwoDmFRVerdict", str(est.iloc[0]["verdict"]))
            macros += macro("CvTwoDmFRRelFinal", _fmt(100 * est.iloc[0]["rel_final"], 1))
    # ---------------- mFR success verdict (R15 methods, the STARVED cell) ----------------
    r15succ = _load(os.path.join(args.root, "r15_methods", "summaries", "cv_success.csv"))
    if r15succ is not None and not r15succ.empty:
        prim = r15succ[r15succ.cell.astype(str).str.startswith("production")]
        est = (prim if not prim.empty else r15succ)
        est = est[est.method.astype(str) == "fr_estimated"]
        if not est.empty:
            macros += macro("CvRfifteenmFRVerdict", str(est.iloc[0]["verdict"]))
            macros += macro("CvRfifteenmFRRelFinal", _fmt(100 * est.iloc[0]["rel_final"], 1))
            macros += macro("CvRfifteenmFRWin", _fmt(est.iloc[0].get("win_rate_final"), 2))

    with open(os.path.join(TAB, "cv_numbers.tex"), "w") as fh:
        fh.write(macros)

    # ---------------- tables ----------------
    def screen_table(subs, cvname, path, caption, label):
        if isinstance(subs, str):
            subs = [subs]
        lines = ["% auto-generated", "\\begin{table}[t]\\centering",
                 f"\\caption{{{caption}}}\\label{{{label}}}",
                 "\\small\\begin{tabular}{lrrrl}", "\\toprule",
                 "cell & final $L_2(F)$ & r.t./N & families & verdict\\\\", "\\midrule"]
        any_rows = False
        for sub in subs:
            st = load_starv(sub)
            cs = _load(os.path.join(args.root, sub, "summaries", "cv_config_summary.csv"))
            if st is None:
                continue
            cmain = cs[cs.method == "abf"] if cs is not None else None
            for _, r in st.iterrows():
                any_rows = True
                l2, rt = "--", "--"
                if cmain is not None:
                    mm = cmain[cmain.cell == r["cell"]]
                    if not mm.empty:
                        if "final_l2_F_med" in mm:
                            l2 = _fmt(mm.iloc[0]["final_l2_F_med"], 3)
                        if "n_round_trips_med" in mm and "n_replicas_med" in mm:
                            rt = _fmt(mm.iloc[0]["n_round_trips_med"] / max(mm.iloc[0]["n_replicas_med"], 1), 1)
                nfam = int(r["n_families"]) if "n_families" in r else int(r.get("n_criteria_fired", 0))
                lines.append(f"{_cell_label(r['cell'])} & {l2} & {rt} & {nfam} & {r['verdict']}\\\\")
        if not any_rows:
            lines.append("\\multicolumn{5}{c}{(pending)}\\\\")
        lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
        with open(os.path.join(TAB, path), "w") as fh:
            fh.write("\n".join(lines) + "\n")

    screen_table(["r15", "r14"], "R15", "cv_r15_screen.tex",
                 "Pentane $R_{15}$ and butane $R_{14}$ ABF-only starvation screen (round-trips per replica; families = distinct evidence families, $\\geq 2 \\Rightarrow$ starved).", "tab:cv_r15_screen")
    screen_table("2d", "2D", "cv_2d_screen.tex",
                 "Two-dimensional torsion $(\\varphi_1,\\varphi_2)$ ABF-only starvation screen.", "tab:cv_2d_screen")

    # 2-D validation tolerances
    lines = ["% auto-generated", "\\begin{table}[t]\\centering",
             "\\caption{Two-dimensional ABF mathematical validation.}\\label{tab:cv_2d_validation}",
             "\\begin{tabular}{ll}", "\\toprule", "check & result\\\\", "\\midrule",
             "dual biorthogonality $w_a\\!\\cdot\\!\\nabla\\varphi_c=\\delta_{ac}$ & $<10^{-9}$ (test)\\\\",
             "analytic $\\nabla\\!\\cdot w_a$ vs FD & $<10^{-4}$ (test)\\\\",
             "Poisson exact-gradient recovery & $<10^{-9}$ (test)\\\\",
             "decoupled exact gate max abs err & \\CvTwoDGateExact\\\\",
             f"decoupled 2-D thermal $L_2$ (grid \\CvGateGridFine) & \\CvGateLtwo~kT\\\\",
             "Gram $\\max\\kappa$ / regularisations & \\CvGateCondMax\\ / \\CvGateReg\\\\",
             "\\bottomrule", "\\end{tabular}", "\\end{table}"]
    with open(os.path.join(TAB, "cv_2d_validation.tex"), "w") as fh:
        fh.write("\n".join(lines) + "\n")

    # cross-case starvation map
    lines = ["% auto-generated", "\\begin{table}[t]\\centering",
             "\\caption{Cross-case ABF starvation synthesis along the biased coordinate.}\\label{tab:cv_starvation_map}",
             "\\begin{tabular}{lll}", "\\toprule",
             "coordinate & molecule & ABF starved?\\\\", "\\midrule",
             "$\\varphi_1$ (1-D dihedral) & butane/pentane & no (prior work)\\\\",
             "$R_{15}$ (1-D distance) & pentane & \\CvRfifteenStarv\\\\",
             "$R_{14}$ (1-D distance) & butane & \\CvRfourteenStarv\\\\",
             "$(\\varphi_1,\\varphi_2)$ (2-D) & pentane & \\CvTwoDStarvPrimary\\ (primary)\\\\",
             "\\bottomrule", "\\end{tabular}", "\\end{table}"]
    with open(os.path.join(TAB, "cv_starvation_map.tex"), "w") as fh:
        fh.write("\n".join(lines) + "\n")

    # 2-D methods comparison table (if a methods stage ran)
    cs2 = _load(os.path.join(args.root, "2d_methods", "summaries", "cv_config_summary.csv"))
    lines = ["% auto-generated", "\\begin{table}[t]\\centering",
             "\\caption{Two-dimensional production comparison (median over seeds).}\\label{tab:cv_2d_methods}",
             "\\begin{tabular}{llrrrr}", "\\toprule",
             "cell & method & $L_2(F)$ & basins & cond.\\ TV & anc.\\ ESS/N\\\\", "\\midrule"]
    if cs2 is not None and (cs2.name.astype(str).str.contains("fr_").any()):
        prod = cs2[cs2.cell.astype(str).str.contains("joint2d")]
        if "stage" in prod:
            prod = prod[prod.stage.astype(str) == "production"]
        for cell, sub in prod.groupby("cell"):
            for _, r in sub.iterrows():
                ess = r.get("final_ancestor_ess_med", np.nan); nrep = r.get("n_replicas_med", 2048)
                essn = ess / nrep if np.isfinite(ess) else np.nan
                lines.append(f"{_cell_label(cell)} & {str(r['name']).replace('_',' ')} & "
                             f"{_fmt(r.get('final_l2_F_med'),3)} & {_fmt(r.get('n_basins_visited_med'),0)} & "
                             f"{_fmt(r.get('cond_tv_weighted_med'),3)} & {_fmt(essn,2)}\\\\")
    else:
        lines.append("\\multicolumn{6}{c}{(methods stage not run / pending)}\\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    with open(os.path.join(TAB, "cv_2d_methods.tex"), "w") as fh:
        fh.write("\n".join(lines) + "\n")

    # R15 methods comparison table (the STARVED cell -- headline Q1 result)
    csr = _load(os.path.join(args.root, "r15_methods", "summaries", "cv_config_summary.csv"))
    lines = ["% auto-generated", "\\begin{table}[t]\\centering",
             "\\caption{R15 (starved cell) production comparison (median over seeds).}\\label{tab:cv_r15_methods}",
             "\\begin{tabular}{llrrrr}", "\\toprule",
             "cell & method & $L_2(F)$ & \\#round-trips & cond.\\ TV & anc.\\ ESS/N\\\\", "\\midrule"]
    if csr is not None and (csr.name.astype(str).str.contains("fr_").any() or csr.name.astype(str).str.contains("opes").any()):
        prod = csr[csr.stage.astype(str) == "production"] if "stage" in csr.columns else csr
        for cell, sub in prod.groupby("cell"):
            for _, r in sub.iterrows():
                ess = r.get("final_ancestor_ess_med", np.nan); nrep = r.get("n_replicas_med", 1024)
                essn = ess / nrep if np.isfinite(ess) else np.nan
                lines.append(f"{_cell_label(cell)} & {str(r['name']).replace('_',' ')} & "
                             f"{_fmt(r.get('final_l2_F_med'),3)} & {_fmt(r.get('n_round_trips_med'),0)} & "
                             f"{_fmt(r.get('dist_cond_tv_weighted_med'),3)} & {_fmt(essn,2)}\\\\")
    else:
        lines.append("\\multicolumn{6}{c}{(R15 methods stage not run / pending)}\\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    with open(os.path.join(TAB, "cv_r15_methods.tex"), "w") as fh:
        fh.write("\n".join(lines) + "\n")

    print(f"[assets] wrote cv_numbers.tex + 6 tables to {TAB}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
