#!/usr/bin/env python3
"""Generate LaTeX macros for the WCA follow-up report subsections (Parts B-F).

Writes ``report/tables/wca_followup_numbers.tex`` with ``\\newcommand`` macros
(prefix ``WCAF``). It reads whichever summary CSVs already exist and emits a
placeholder ``\\WCAF...{--}`` for any study that has not been aggregated yet, so
the report ALWAYS compiles whether or not the GPU runs have finished.

Inputs (any subset; missing ones -> placeholders):
  --starvation  results/wca_phase_diagram/production/starvation/wca_phase_diagram_augmented.csv
  --representative results/wca_representative/summaries/matched_seed_table.csv
  --equal-compute  results/wca_equal_compute/summaries/equal_compute_summary.csv
  --frozen         results/wca_frozen_bias/summaries/frozen_bias_summary.csv

Usage:
  python scripts/make_followup_report_assets.py \
      --starvation results/wca_phase_diagram/production/starvation/wca_phase_diagram_augmented.csv \
      --representative results/wca_representative/summaries/matched_seed_table.csv \
      --equal-compute results/wca_equal_compute/summaries/equal_compute_summary.csv \
      --frozen results/wca_frozen_bias/summaries/frozen_bias_summary.csv
"""
from __future__ import annotations

import argparse
import csv
import os

import numpy as np

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "report", "tables",
                   "wca_followup_numbers.tex")


def _read(path):
    if not path or not os.path.exists(path):
        return None
    return list(csv.DictReader(open(path)))


def _f(rows, key):
    out = []
    for r in rows:
        try:
            out.append(float(r[key]))
        except Exception:
            pass
    return out


def _spearman(x, y):
    x = np.asarray(x, float); y = np.asarray(y, float)
    m = np.isfinite(x) & np.isfinite(y)
    x, y = x[m], y[m]
    if x.size < 3:
        return float("nan")
    rx = np.argsort(np.argsort(x)); ry = np.argsort(np.argsort(y))
    rx = rx - rx.mean(); ry = ry - ry.mean()
    denom = np.sqrt((rx ** 2).sum() * (ry ** 2).sum())
    return float((rx * ry).sum() / denom) if denom > 0 else float("nan")


def cmd(name, val):
    return f"\\newcommand{{\\{name}}}{{{val}}}"


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--starvation", default=None)
    ap.add_argument("--representative", default=None)
    ap.add_argument("--equal-compute", default=None)
    ap.add_argument("--frozen", default=None)
    ap.add_argument("--starved-threshold", type=float, default=0.05)
    ap.add_argument("--easy-threshold", type=float, default=0.02)
    args = ap.parse_args(argv)

    lines = [r"% Auto-generated by scripts/make_followup_report_assets.py. Do not edit by hand.",
             r"% Macros for the WCA follow-up subsections (prefix WCAF)."]

    # ---- starvation (Part B) ----
    st = _read(args.starvation)
    if st:
        est = [r for r in st if r["method"] == "fr_estimated"]
        abf_err = _f(est, "abf_final_l2_f_median")
        gain = _f(est, "median_gain_pct_F")
        rho = _spearman(abf_err, gain)
        starved = [r for r in est if float(r["abf_final_l2_f_median"]) >= args.starved_threshold]
        easy = [r for r in est if float(r["abf_final_l2_f_median"]) <= args.easy_threshold]
        starved_gain = _f(starved, "median_gain_pct_F")
        easy_gain = _f(easy, "median_gain_pct_F")
        # correlation with beta*h for contrast
        bh = _f(est, "beta_h")
        rho_bh = _spearman(bh, gain)
        worst = min(est, key=lambda r: float(r["median_gain_pct_F"]))
        lines += [
            cmd("WCAFStarvNCells", len(est)),
            cmd("WCAFStarvNStarved", len(starved)),
            cmd("WCAFStarvNEasy", len(easy)),
            cmd("WCAFStarvThreshold", f"{args.starved_threshold:g}"),
            cmd("WCAFStarvEasyThreshold", f"{args.easy_threshold:g}"),
            cmd("WCAFStarvRhoErr", f"{rho:.2f}"),
            cmd("WCAFStarvRhoBetaH", f"{rho_bh:.2f}"),
            cmd("WCAFStarvStarvedMedGain", f"{np.median(starved_gain):.0f}" if starved_gain else "--"),
            cmd("WCAFStarvStarvedMinGain", f"{min(starved_gain):.0f}" if starved_gain else "--"),
            cmd("WCAFStarvStarvedMaxGain", f"{max(starved_gain):.0f}" if starved_gain else "--"),
            cmd("WCAFStarvEasyMedGain", f"{np.median(easy_gain):.0f}" if easy_gain else "--"),
            cmd("WCAFStarvWorstGain", f"{float(worst['median_gain_pct_F']):.0f}"),
            cmd("WCAFStarvWorstCell", f"$\\beta{{=}}{float(worst['beta']):g},\\,h{{=}}{float(worst['h']):g}$"),
        ]
    else:
        for n in ["WCAFStarvNCells", "WCAFStarvNStarved", "WCAFStarvNEasy", "WCAFStarvThreshold",
                  "WCAFStarvEasyThreshold", "WCAFStarvRhoErr", "WCAFStarvRhoBetaH",
                  "WCAFStarvStarvedMedGain", "WCAFStarvStarvedMinGain", "WCAFStarvStarvedMaxGain",
                  "WCAFStarvEasyMedGain", "WCAFStarvWorstGain", "WCAFStarvWorstCell"]:
            lines.append(cmd(n, "--"))

    # ---- representative + adaptive (Parts C/D) ----
    rep = _read(args.representative)
    def rep_get(tag_sub, method, key):
        if not rep:
            return None
        for r in rep:
            if tag_sub in r["physics_tag"] and r["name"] == method:
                try:
                    return float(r[key])
                except Exception:
                    return None
        return None
    if rep:
        lines += [
            cmd("WCAFRepNSeeds", max((int(r["n_seeds"]) for r in rep), default=0)),
            cmd("WCAFAdaptStarvedFixedGain", _fmt(rep_get("b1_h2", "fr_estimated", "median_gain_pct_F"))),
            cmd("WCAFAdaptStarvedAdaptGain", _fmt(rep_get("b1_h2", "fr_estimated_adaptive", "median_gain_pct_F"))),
            cmd("WCAFAdaptEasyFixedGain", _fmt(rep_get("b4_h1", "fr_estimated", "median_gain_pct_F"))),
            cmd("WCAFAdaptEasyAdaptGain", _fmt(rep_get("b4_h1", "fr_estimated_adaptive", "median_gain_pct_F"))),
            cmd("WCAFAdaptEasyAdaptEventFrac", _fmt(rep_get("b4_h1", "fr_estimated_adaptive", "fr_event_fraction_median"), 4)),
            cmd("WCAFAdaptStarvedAdaptEventFrac", _fmt(rep_get("b1_h2", "fr_estimated_adaptive", "fr_event_fraction_median"), 4)),
        ]
    else:
        for n in ["WCAFRepNSeeds", "WCAFAdaptStarvedFixedGain", "WCAFAdaptStarvedAdaptGain",
                  "WCAFAdaptEasyFixedGain", "WCAFAdaptEasyAdaptGain",
                  "WCAFAdaptEasyAdaptEventFrac", "WCAFAdaptStarvedAdaptEventFrac"]:
            lines.append(cmd(n, "--"))

    # ---- equal compute (Part E) ----
    ec = _read(args.equal_compute)
    if ec:
        # for the starved cell b1_h2: ABF at 3 budgets vs fr_estimated at base
        def ec_get(tag_sub, method, N, T):
            for r in ec:
                if (tag_sub in r["physics_tag"] and r["method"] == method
                        and int(r["n_replicas"]) == N and int(r["n_steps"]) == T):
                    try:
                        return float(r["l2_f_median"])
                    except Exception:
                        return None
            return None
        lines += [
            cmd("WCAFECStarvedABFBase", _fmt(ec_get("b1_h2", "abf", 1024, 120000))),
            cmd("WCAFECStarvedABFWide", _fmt(ec_get("b1_h2", "abf", 2048, 60000))),
            cmd("WCAFECStarvedABFLong", _fmt(ec_get("b1_h2", "abf", 512, 240000))),
            cmd("WCAFECStarvedFR", _fmt(ec_get("b1_h2", "fr_estimated", 1024, 120000))),
        ]
    else:
        for n in ["WCAFECStarvedABFBase", "WCAFECStarvedABFWide", "WCAFECStarvedABFLong", "WCAFECStarvedFR"]:
            lines.append(cmd(n, "--"))

    # ---- frozen bias (Part F) ----
    fz = _read(args.frozen)
    if fz:
        def fz_get(tag_sub, src, key):
            for r in fz:
                if tag_sub in r["physics_tag"] and r["source_method"] == src:
                    try:
                        return float(r[key])
                    except Exception:
                        return None
            return None
        lines += [
            cmd("WCAFFrozenStarvedABFRecon", _fmt(fz_get("b1_h2", "abf", "frozen_recon_l2_f_median"))),
            cmd("WCAFFrozenStarvedFRRecon", _fmt(fz_get("b1_h2", "fr_estimated", "frozen_recon_l2_f_median"))),
            cmd("WCAFFrozenStarvedAdaptRecon", _fmt(fz_get("b1_h2", "fr_estimated_adaptive", "frozen_recon_l2_f_median"))),
            cmd("WCAFFrozenEasyABFRecon", _fmt(fz_get("b4_h1", "abf", "frozen_recon_l2_f_median"))),
            cmd("WCAFFrozenEasyFRRecon", _fmt(fz_get("b4_h1", "fr_estimated", "frozen_recon_l2_f_median"))),
        ]
    else:
        for n in ["WCAFFrozenStarvedABFRecon", "WCAFFrozenStarvedFRRecon", "WCAFFrozenStarvedAdaptRecon",
                  "WCAFFrozenEasyABFRecon", "WCAFFrozenEasyFRRecon"]:
            lines.append(cmd(n, "--"))

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(lines)-2} macros)")


def _fmt(x, nd=4):
    if x is None or not np.isfinite(x):
        return "--"
    return f"{x:.{nd}f}" if abs(x) < 100 else f"{x:.0f}"


if __name__ == "__main__":
    raise SystemExit(main())
