#!/usr/bin/env python3
"""Generate LaTeX macros for the OPES_METAD baseline comparison (prefix ``OPES``).

Writes ``report/tables/opes_numbers.tex`` with ``\\newcommand`` macros read from
the OPES summary CSVs. Emits ``{--}`` placeholders for anything not yet
aggregated, so the report ALWAYS compiles.

Inputs (any subset; missing -> placeholders):
  --vs-baselines  results/opes_wca/summaries/opes_vs_baselines.csv
  --tuning        results/opes_wca/summaries/opes_tuning.csv
  --cell-summary  results/opes_wca/summaries/opes_cell_summary.csv

Usage:
  python scripts/make_opes_report_assets.py \
      --vs-baselines results/opes_wca/summaries/opes_vs_baselines.csv \
      --tuning results/opes_wca/summaries/opes_tuning.csv
"""
from __future__ import annotations

import argparse
import csv
import os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "report", "tables",
                   "opes_numbers.tex")

CELL_LABEL = {"b1_h2_w2_n10_a1.5": "Starved", "b2_h6_w2_n10_a1.5": "Intermediate",
              "b4_h1_w2_n10_a1.5": "Easy", "b1_h4_w2_n10_a1.5": "b1h4",
              "b2_h4_w2_n10_a1.5": "b2h4", "b4_h2_w2_n10_a1.5": "b4h2"}
CELL_TAG = {"b1_h2_w2_n10_a1.5": "StarvedCell", "b2_h6_w2_n10_a1.5": "InterCell",
            "b4_h1_w2_n10_a1.5": "EasyCell"}


def _read(path):
    if not path or not os.path.exists(path):
        return None
    return list(csv.DictReader(open(path)))


def cmd(name, val):
    # Use \def instead of \newcommand to avoid tectonic v2 context-sensitivity
    return f"\\def\\{name}{{{val}}}"


def _fmt(val, nd=4):
    try:
        v = float(val)
        return f"{v:.{nd}f}" if abs(v) < 100 else f"{v:.0f}"
    except Exception:
        return "--"


def _pct(val):
    try:
        return f"{float(val):+.1f}\\%"
    except Exception:
        return "--"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--vs-baselines", default="results/opes_wca/summaries/opes_vs_baselines.csv")
    ap.add_argument("--tuning", default="results/opes_wca/summaries/opes_tuning.csv")
    ap.add_argument("--cell-summary", default="results/opes_wca/summaries/opes_cell_summary.csv")
    args = ap.parse_args(argv)
    lines = [r"% Auto-generated by make_opes_report_assets.py. Do not edit by hand.",
             r"% OPES_METAD comparison macros (prefix OPES)."]
    vs = _read(args.vs_baselines)
    tuning = _read(args.tuning)
    cell_sum = _read(args.cell_summary)
    # ---- vs-baselines for the 3 representative cells ----
    if vs:
        by_tag = {r["physics_tag"]: r for r in vs}
        for tag, sfx in CELL_TAG.items():
            r = by_tag.get(tag)
            lines += [
                cmd(f"OPES{sfx}LtwoF", _fmt(r["opes_l2_f"]) if r else "--"),
                cmd(f"OPES{sfx}LtwoFp", _fmt(r["opes_l2_fp"]) if r else "--"),
                cmd(f"ABF{sfx}LtwoF", _fmt(r["abf_l2_f"]) if r else "--"),
                cmd(f"MFR{sfx}LtwoF", _fmt(r["mfr_l2_f"]) if r else "--"),
                cmd(f"OPES{sfx}VsABFpct", _pct(r["opes_vs_abf_pct"]) if r else "--"),
                cmd(f"OPES{sfx}VsMFRpct", _pct(r["opes_vs_mfr_pct"]) if r else "--"),
                cmd(f"OPES{sfx}BestBarrier", str(r["opes_best_barrier"]) if r else "--"),
            ]
    else:
        for tag, sfx in CELL_TAG.items():
            for prefix in ["OPES","ABF","MFR"]:
                for suf in ["LtwoF","LtwoFp"]:
                    lines.append(cmd(f"{prefix}{sfx}{suf}", "--"))
    # ---- tuning summary ----
    if tuning:
        best_rows = {}
        for r in tuning:
            tag = r["physics_tag"]
            try:
                v = float(r["l2_f_median"])
            except Exception:
                v = float("inf")
            if tag not in best_rows or v < float(best_rows[tag]["l2_f_median"]):
                best_rows[tag] = r
        for tag, sfx in CELL_TAG.items():
            r = best_rows.get(tag)
            lines += [
                cmd(f"OPES{sfx}TuneBarrier", str(r["opes_barrier"]) if r else "--"),
                cmd(f"OPES{sfx}TunePace", str(r["opes_pace"]) if r else "--"),
                cmd(f"OPES{sfx}TuneLtwoF", _fmt(r["l2_f_median"]) if r else "--"),
            ]
    else:
        for tag, sfx in CELL_TAG.items():
            for suf in ["TuneBarrier","TunePace","TuneLtwoF"]:
                lines.append(cmd(f"OPES{sfx}{suf}", "--"))
    # ---- OPES summary stats ----
    if vs:
        opes_l2f_vals = []
        for r in vs:
            try:
                opes_l2f_vals.append(float(r["opes_l2_f"]))
            except Exception:
                pass
        lines += [cmd("OPESNRepCells", str(len(vs))),
                  cmd("OPESEstimator", "mean-force reconstruction")]
    # ---- toy summaries (metastability + entropic bottleneck) ----
    for toy, sfx in [("meta", "Meta"), ("eb", "EB")]:
        rows = _read(f"results/opes_toys/summaries/opes_{toy}_summary.csv")
        r = rows[0] if rows else None
        for key, suf in [("opes_l2_f", "LtwoF"), ("opes_l2_fp", "LtwoFp"),
                         ("abf_l2_f", "ABFLtwoF"), ("mfr_l2_f", "MFRLtwoF"),
                         ("opes_best_barrier", "Barrier"), ("opes_neff", "Neff"),
                         ("opes_vs_abf_pct", "VsABFpct"), ("opes_vs_mfr_pct", "VsMFRpct")]:
            val = "--"
            if r:
                if suf.endswith("pct"):
                    val = _pct(r[key])
                elif suf == "Barrier":
                    try:
                        val = f"{float(r[key]):g}"   # 4.0 -> "4"
                    except Exception:
                        val = "--"
                else:
                    val = _fmt(r[key])
            lines.append(cmd(f"OPES{sfx}{suf}", val))
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"[write] {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
