#!/usr/bin/env python
"""Emit LaTeX macros for the atomistic neutrality controls and the entropic gateway.

Writes ``report/tables/valine_numbers.tex`` (prefix ``Val``) and
``report/tables/gateway_numbers.tex`` (prefix ``Gw``) from the closure and anchor
artifacts.  Uses ``\\def`` rather than ``\\newcommand``, matching the newer macro files --
tectonic v2 is context-sensitive about ``\\newcommand`` in this preamble position.

Every macro is defined as ``--`` first and only overwritten when the underlying artifact
exists, so the report compiles with visible placeholders rather than an undefined-macro
error when a run has not been aggregated.

    python scripts/make_neutrality_report_assets.py
"""
from __future__ import annotations

import json
import os
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
TABLES = os.path.join(ROOT, "report", "tables")

ALA_MACROS = [
    "AlaSeeds", "AlaWalkers", "AlaTrun", "AlaWindow", "AlaWindows", "AlaRefAgg",
    "AlaRefdG", "AlaRefdGse", "AlaRefFse", "AlaRefSyst", "AlaVerdict", "AlaThreshold",
    "AlaGainMain", "AlaGainCIlo", "AlaGainCIhi", "AlaGainWins", "AlaGainRefeq",
    "AlaRateLo", "AlaRateHi", "AlaEventLo", "AlaEventHi", "AlaEventSpan",
    "AlaEssHi", "AlaEssLo", "AlaEssGate", "AlaWmaxHi", "AlaGainRateMid", "AlaGainRateHi",
    "AlaRarePop", "AlaRareOcc", "AlaRareHitLo", "AlaRareHitHi",
    "AlaRareBarrier", "AlaPsiBarrierMed", "AlaPsiBarrierMax",
]
VAL_MACROS = [
    "ValRegions", "ValSeeds", "ValWalkers", "ValTrun", "ValFirstTouch", "ValThit",
    "ValTest", "ValRarePop", "ValRareOccTarget", "ValPmfErr", "ValPmfErrLo",
    "ValPmfErrHi", "ValMarginalTV", "ValBelowHalf", "ValBelowHalfThresh", "ValDmax",
    "ValPsiMatched", "ValPsiOriginal", "ValPsiThresh", "ValEntriesNaive",
    "ValEntriesCorridor", "ValVerdict",
]
WCS_MACROS = [
    "WcsSeeds", "WcsCell", "WcsSteps", "WcsReplicas", "WcsRate",
    "WcsEstGain", "WcsEstCIlo", "WcsEstCIhi", "WcsEstWins", "WcsEstEss", "WcsEstAnc",
    "WcsShamGain", "WcsShamCIlo", "WcsShamCIhi", "WcsShamCIloNinety",
    "WcsShamCIhiNinety", "WcsShamTost",
    "WcsDirect", "WcsDirectCIlo", "WcsDirectCIhi", "WcsDirectWins",
    "WcsOracleGain", "WcsOracleCIlo", "WcsOracleCIhi",
    "WcsOracleDirect", "WcsOracleDirectCIlo", "WcsOracleDirectCIhi",
    "WcsMismatch", "WcsVerdict", "WcsCritOne", "WcsCritTwo",
    "WcsAbfRoundTrips", "WcsEstRoundTrips", "WcsShamRoundTrips",
]
GW_MACROS = [
    "GwCells", "GwSuff", "GwInter", "GwEst", "GwDisc", "GwSeeds", "GwWalkers", "GwTrun",
    "GwBarrierLo", "GwBarrierHi", "GwAnchorBeta", "GwAnchorS", "GwAnchorR",
    "GwAnchorThit", "GwAnchorTest", "GwAnchorBelowHalf", "GwAnchorOccTarget",
    "GwEstGain", "GwEstCIlo", "GwEstCIhi", "GwEstWins", "GwEstGamma", "GwEstEss",
    "GwEstWmax", "GwEstDeficit", "GwEstTest", "GwOracleGain", "GwOracleCIlo",
    "GwOracleCIhi", "GwOracleWins", "GwOracleGamma", "GwOracleEss", "GwOracleDeficit",
    "GwShamGain", "GwShamCIlo", "GwShamCIhi", "GwShamWins", "GwShamVerdict",
    "GwShamMismatch", "GwShamRangeLo", "GwShamRangeHi", "GwShamExclZero",
    "GwFrozenGamma", "GwFrozenOracleGain", "GwFrozenEstGain",
    "GwFrozenOracleEss", "GwFrozenEstEss", "GwFrozenOracleWmax", "GwOneRightGain",
    "GwOneRightCIlo", "GwOneRightCIhi", "GwOneRightWins", "GwEssGate", "GwWmaxGate",
    # confirmatory run (fresh seeds, frozen rates) -- prefix Gwc
    "GwcSeeds", "GwcEstGain", "GwcEstCIlo", "GwcEstCIhi", "GwcEstWins", "GwcEstEss",
    "GwcEstWmax", "GwcShamGain", "GwcShamCIlo", "GwcShamCIhi", "GwcShamTost",
    "GwcDirect", "GwcDirectCIlo", "GwcDirectCIhi", "GwcDirectWins",
    "GwcOracleDirect", "GwcOracleDirectCIlo", "GwcOracleDirectCIhi",
    "GwcFrozen", "GwcFrozenCIlo", "GwcFrozenCIhi",
    "GwcShamFrozen", "GwcShamFrozenCIlo", "GwcShamFrozenCIhi",
    "GwcDirectFrozen", "GwcDirectFrozenCIlo", "GwcDirectFrozenCIhi",
    "GwcOneRight", "GwcOneRightCIlo", "GwcOneRightCIhi", "GwcOneRightWins",
    "GwcShamOracleTost", "GwcShamOracleCIlo", "GwcShamOracleCIhi", "GwcMargin",
    # beta-scaling audit -- prefix Bs
    "BsTauEstFold", "BsBetaFold", "BsTestFracFold", "BsTauHit", "BsMeanErrFold",
    "BsBetaHkT",
]


def emit(path, macros, values, source):
    lines = [f"% Auto-generated by scripts/{os.path.basename(__file__)} -- do not edit.",
             f"% Source: {source}"]
    for m in macros:
        lines.append(f"\\def\\{m}{{--}}")
    for m, v in values.items():
        if m not in macros:
            raise SystemExit(f"macro {m} not declared in the placeholder list")
        lines.append(f"\\def\\{m}{{{v}}}")
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {path}  ({len(values)}/{len(macros)} macros populated)")


def alanine():
    """Alanine macros, from the artifacts that survive.

    The N2048 stage's decision JSON was overwritten by the later reference-equilibrium
    stage (the analysis wrote unsuffixed filenames), so the headline is quoted from the
    N4096 stage, which has its own artifact.  A number whose artifact no longer exists does
    not go in the paper.
    """
    p4 = os.path.join(ROOT, "results/alanine_oracle/pilot/analysis/pilot_decision_N4096.json")
    pr = os.path.join(ROOT, "results/alanine_oracle/pilot/analysis/pilot_decision_N2048_refeq.json")
    lp = os.path.join(ROOT, "results/alanine_oracle/rate_ladder/analysis/ladder_summary.json")
    bp = os.path.join(ROOT, "results/alanine/reference/bootstrap.json")
    if not os.path.exists(p4):
        return {}, "results/alanine_oracle (missing)"
    d = json.load(open(p4))
    eq = d["primary_kernel_matched_integrated_FES"]["equilibrium"]
    v = {
        "AlaSeeds": d["n_paired_seeds"], "AlaWalkers": 4096, "AlaTrun": 100,
        "AlaWindow": f"{d['window_ps'][0]:g}--{d['window_ps'][1]:g}",
        "AlaWindows": 576, "AlaRefAgg": "9.216",
        "AlaVerdict": "equivalent", "AlaThreshold": "-10",
        "AlaGainMain": f"{100 * eq['median']:+.3f}",
        "AlaGainCIlo": f"{100 * eq['lo']:+.3f}",
        "AlaGainCIhi": f"{100 * eq['hi']:+.3f}",
        "AlaGainWins": f"{int(round(eq['win_rate'] * eq['n']))}/{eq['n']}",
        "AlaEssGate": "0.30",
    }
    if os.path.exists(pr):
        e2 = json.load(open(pr))["primary_kernel_matched_integrated_FES"]["equilibrium"]
        v["AlaGainRefeq"] = f"{100 * e2['median']:+.3f}"
    if os.path.exists(bp):
        b = json.load(open(bp))
        v["AlaRefdG"] = f"{b['dG_kT']:.3f}"
        v["AlaRefdGse"] = f"{b['dG_se_kT']:.3f}"
        v["AlaRefFse"] = f"{b['F_se_median_kT']:.3f}"
        v["AlaRefSyst"] = "0.25"
        v["AlaRarePop"] = f"{b['P_phi_pos']:.4f}"
    if os.path.exists(lp):
        L = sorted(json.load(open(lp)), key=lambda r: r["fr_rate"])
        lo, hi = L[0], L[-1]
        v["AlaRateLo"] = f"{lo['fr_rate']:g}"
        v["AlaRateHi"] = f"{hi['fr_rate']:g}"
        v["AlaEventLo"] = f"{lo['events']}"
        v["AlaEventHi"] = f"{hi['events']}"
        # Span quoted on EVENTS, with the denominator named in the text: the rate ratio
        # (22.5x) and the per-opportunity intensity ratio (20.4x) both differ from it, and
        # two documents in this repository quote different ones.
        v["AlaEventSpan"] = f"{hi['events'] / lo['events']:.0f}"
        v["AlaEssHi"] = f"{lo['ess_age_min']:.3f}"
        v["AlaEssLo"] = f"{hi['ess_age_min']:.3f}"
        v["AlaWmaxHi"] = f"{hi['wmax']:.4f}"
        v["AlaGainRateMid"] = f"{100 * L[1]['median']:+.3f}"
        v["AlaGainRateHi"] = f"{100 * hi['median']:+.3f}"
    # measured in the accepted reference; see ALANINE_REFERENCE_HANDOFF
    v["AlaPsiBarrierMed"] = "0.17"
    v["AlaPsiBarrierMax"] = "0.75"
    v["AlaRareBarrier"] = "15.8"
    v["AlaRareHitLo"] = "3.1"
    v["AlaRareHitHi"] = "4.1"
    v["AlaRareOcc"] = "5.6"
    return v, "results/alanine_oracle + results/alanine/reference"


def valine():
    p = os.path.join(ROOT, "results/valine/closure/provenance.json")
    if not os.path.exists(p):
        return {}, "results/valine/closure (missing)"
    d = json.load(open(p))
    s = d["summary"]
    reg = s["per_region"]
    rare = min(reg, key=lambda x: x["pilot_population"])
    naive_zero = [r for r in reg if r["entries_naive_mean"] == 0]
    v = {
        "ValRegions": len(reg),
        "ValSeeds": d["run_meta"]["n_seeds"],
        "ValWalkers": d["run_meta"]["n_replicas"],
        "ValTrun": f"{s['T_run_ps']:.0f}",
        "ValFirstTouch": f"{s['first_touch_ps_worst']:.1f}",
        "ValThit": f"{s['T_hit_ps_worst']:.0f}",
        "ValTest": f"{s['T_est_ps_worst']:.0f}",
        "ValRarePop": f"{rare['pilot_population']:.4f}",
        "ValRareOccTarget": f"{rare['occ_over_target_median']:.2f}",
        "ValPmfErr": f"{s['final_pmf_err_kT']:.3f}",
        "ValPmfErrLo": f"{s['final_pmf_err_kT_range'][0]:.3f}",
        "ValPmfErrHi": f"{s['final_pmf_err_kT_range'][1]:.3f}",
        "ValMarginalTV": f"{s['marginal_tv']:.3f}",
        "ValBelowHalf": f"{s['frac_below_half_worst']:.3f}",
        "ValBelowHalfThresh": f"{d['thresholds']['deficit_frac']:.2f}",
        "ValDmax": f"{s['D_max_second_half']:.3f}",
        "ValPsiMatched": f"{s['psi_worst_tv_matched']:.3f}",
        "ValPsiOriginal": f"{s['psi_worst_tv_original']:.3f}",
        "ValPsiThresh": f"{d['thresholds']['psi_tv']:.2f}",
        "ValEntriesNaive": ", ".join(r["region"] for r in naive_zero) or "none",
        "ValEntriesCorridor": "/".join(f"{r['entries_corridor_aware_mean']:.0f}"
                                       for r in naive_zero) or "--",
        "ValVerdict": "FAIL-B (ABF already sufficient)",
    }
    return v, "results/valine/closure/provenance.json"


def gateway():
    fp = os.path.join(ROOT, "results/gateway_phase/production/phase_classification.frozen.json")
    ap = os.path.join(ROOT, "results/gateway_anchor/production/anchor_summary.json")
    if not os.path.exists(fp):
        return {}, "results/gateway_phase (missing)"
    f = json.load(open(fp))
    c, prov, anc = f["regime_counts"], f["provenance"], f["anchor"]
    v = {
        "GwCells": len(f["table"]),
        "GwSuff": c["ABF-sufficient"], "GwInter": c["intermediate"],
        "GwEst": c["establishment-limited"], "GwDisc": c["discovery-limited"],
        "GwSeeds": len(prov["seeds"]), "GwWalkers": prov["n_walkers"],
        "GwTrun": f"{prov['T_total']:g}",
        "GwBarrierLo": f"{min(t['barrier_kT'] for t in f['table']):.1f}",
        "GwBarrierHi": f"{max(t['barrier_kT'] for t in f['table']):.1f}",
        "GwAnchorBeta": f"{anc['beta']:g}", "GwAnchorS": f"{anc['s']:g}",
        "GwAnchorR": f"{anc['r']:g}",
        "GwAnchorThit": f"{anc['T_hit_frac']:.3f}",
        "GwAnchorTest": f"{anc['T_est_frac']:.3f}",
        "GwAnchorBelowHalf": f"{anc['below_half_frac']:.3f}",
        "GwAnchorOccTarget": f"{anc['occ_over_target']:.3f}",
    }
    src = "phase_classification.frozen.json"
    if os.path.exists(ap):
        a = json.load(open(ap))
        v["GwEssGate"] = f"{a['ess_gate']:.2f}"
        v["GwWmaxGate"] = f"{a['wmax_gate']:.2f}"
        v["GwShamMismatch"] = a["sham_count_mismatches"]
        v["GwFrozenGamma"] = f"{a['gamma_frozen']:g}"
        for arm, pre in (("fr_estimated", "GwEst"), ("fr_oracle", "GwOracle")):
            b = a["best_healthy"].get(arm)
            if b:
                v[f"{pre}Gain"] = f"{b['int_l2_f_pct']:.2f}"
                v[f"{pre}CIlo"] = f"{b['int_l2_f_ci_lo']:.2f}"
                v[f"{pre}CIhi"] = f"{b['int_l2_f_ci_hi']:.2f}"
                v[f"{pre}Wins"] = f"{b['int_l2_f_wins']}/{b['n_seeds']}"
                v[f"{pre}Gamma"] = f"{b['gamma']:g}"
                v[f"{pre}Ess"] = f"{b['min_ess_frac']:.3f}"
                v[f"{pre}Deficit"] = f"{b['integrated_deficit_pct']:.1f}"
                if pre == "GwEst":
                    v["GwEstWmax"] = f"{b['max_wmax']:.3f}"
                    v["GwEstTest"] = f"{b['T_est_pct']:.1f}"
        # The sham across EVERY (rate, init) cell, not just the headline row: the claim
        # being made is that it never moves the error, so it has to be checked everywhere.
        sh = [r for r in a["rows"] if r["arm"] == "sham"]
        if sh:
            m = [r["int_l2_f_pct"] for r in sh]
            v["GwShamRangeLo"] = f"{min(m):+.1f}"
            v["GwShamRangeHi"] = f"{max(m):+.1f}"
            v["GwShamExclZero"] = sum(
                1 for r in sh
                if r["int_l2_f_ci_lo"] * r["int_l2_f_ci_hi"] > 0)
        h = a["headline"]
        if "sham" in h:
            s = h["sham"]
            v["GwShamGain"] = f"{s['int_l2_f_pct']:.2f}"
            v["GwShamCIlo"] = f"{s['int_l2_f_ci_lo']:.2f}"
            v["GwShamCIhi"] = f"{s['int_l2_f_ci_hi']:.2f}"
            v["GwShamWins"] = f"{s['int_l2_f_wins']}/{s['n_seeds']}"
            v["GwShamVerdict"] = s["int_l2_f_verdict"]
        for arm, key in (("fr_oracle", "GwFrozenOracle"), ("fr_estimated", "GwFrozenEst")):
            if arm in h:
                v[f"{key}Gain"] = f"{h[arm]['int_l2_f_pct']:.2f}"
                v[f"{key}Ess"] = f"{h[arm]['min_ess_frac']:.3f}"
                if key == "GwFrozenOracle":
                    v["GwFrozenOracleWmax"] = f"{h[arm]['max_wmax']:.3f}"
        # mechanism control: deployable arm at its best health-passing rate
        cand = [r for r in a["rows"] if r["init"] == "one_right"
                and r["arm"] == "fr_estimated" and r["health_ok"]]
        if cand:
            b = min(cand, key=lambda r: r["int_l2_f_pct"])
            v["GwOneRightGain"] = f"{b['int_l2_f_pct']:.2f}"
            v["GwOneRightCIlo"] = f"{b['int_l2_f_ci_lo']:.2f}"
            v["GwOneRightCIhi"] = f"{b['int_l2_f_ci_hi']:.2f}"
            v["GwOneRightWins"] = f"{b['int_l2_f_wins']}/{b['n_seeds']}"
        src += " + anchor_summary.json"
    # ---- confirmatory run + beta-scaling audit -------------------------------
    cp = os.path.join(ROOT, "results/gateway_anchor/confirmatory/confirmatory_summary.json")
    if os.path.exists(cp):
        c = json.load(open(cp))
        pre2 = c["preregistration"]
        mk = pre2["primary_metric"]
        v["GwcSeeds"] = pre2["seeds"]["count"]
        v["GwcMargin"] = f"{pre2['sham_equivalence']['margin_pct'][1]:g}"
        left = {r["arm"]: r for r in c["rows"] if r["init"] == "left"}
        one = {r["arm"]: r for r in c["rows"] if r["init"] == "one_right"}
        e = left["fr_estimated"]
        v["GwcEstGain"] = f"{e[mk + '_pct']:.2f}"
        v["GwcEstCIlo"] = f"{e[mk + '_ci95'][0]:.2f}"
        v["GwcEstCIhi"] = f"{e[mk + '_ci95'][1]:.2f}"
        v["GwcEstWins"] = f"{e[mk + '_wins']}/{e['n_seeds']}"
        v["GwcEstEss"] = f"{e['min_ess_frac']:.3f}"
        v["GwcEstWmax"] = f"{e['max_wmax']:.3f}"
        v["GwcFrozen"] = f"{e['frozen_l2_f_kT_pct']:.2f}"
        v["GwcFrozenCIlo"] = f"{e['frozen_l2_f_kT_ci95'][0]:.2f}"
        v["GwcFrozenCIhi"] = f"{e['frozen_l2_f_kT_ci95'][1]:.2f}"
        sp = left["sham_practical"]
        v["GwcShamGain"] = f"{sp[mk + '_pct']:+.2f}"
        v["GwcShamCIlo"] = f"{sp[mk + '_ci90'][0]:.2f}"
        v["GwcShamCIhi"] = f"{sp[mk + '_ci90'][1]:.2f}"
        v["GwcShamTost"] = ("equivalent" if c["sham_tost"]["sham_practical"]["equivalent"]
                            else "NOT equivalent")
        v["GwcShamFrozen"] = f"{sp['frozen_l2_f_kT_pct']:.2f}"
        v["GwcShamFrozenCIlo"] = f"{sp['frozen_l2_f_kT_ci90'][0]:.2f}"
        v["GwcShamFrozenCIhi"] = f"{sp['frozen_l2_f_kT_ci90'][1]:.2f}"
        so = c["sham_tost"].get("sham_oracle")
        if so:
            v["GwcShamOracleTost"] = ("equivalent" if so["equivalent"]
                                      else "not shown equivalent")
            v["GwcShamOracleCIlo"] = f"{so['ci90'][0]:.2f}"
            v["GwcShamOracleCIhi"] = f"{so['ci90'][1]:.2f}"
        o = one.get("fr_estimated")
        if o:
            v["GwcOneRight"] = f"{o[mk + '_pct']:.2f}"
            v["GwcOneRightCIlo"] = f"{o[mk + '_ci95'][0]:.2f}"
            v["GwcOneRightCIhi"] = f"{o[mk + '_ci95'][1]:.2f}"
            v["GwcOneRightWins"] = f"{o[mk + '_wins']}/{o['n_seeds']}"
        for rec in c.get("direct_vs_sham", []):
            if rec["init"] != "left":
                continue
            pre3 = "Gwc" + ("Direct" if rec["arm"] == "fr_estimated" else "OracleDirect")
            v[pre3] = f"{rec['pct']:.2f}"
            v[pre3 + "CIlo"] = f"{rec['ci95'][0]:.2f}"
            v[pre3 + "CIhi"] = f"{rec['ci95'][1]:.2f}"
            if rec["arm"] == "fr_estimated":
                v["GwcDirectWins"] = f"{rec['wins']}/{rec['n_seeds']}"
                if "frozen_pct" in rec:
                    v["GwcDirectFrozen"] = f"{rec['frozen_pct']:.2f}"
                    v["GwcDirectFrozenCIlo"] = f"{rec['frozen_ci95'][0]:.2f}"
                    v["GwcDirectFrozenCIhi"] = f"{rec['frozen_ci95'][1]:.2f}"
        src += " + confirmatory_summary.json"
    bp = os.path.join(ROOT, "results/gateway_phase/production/beta_scaling_audit.json")
    if os.path.exists(bp):
        b = json.load(open(bp))
        v["BsTauEstFold"] = f"{b['fold_range_tau_est']:.2f}"
        v["BsBetaFold"] = f"{b['beta_fold']:.0f}"
        v["BsTestFracFold"] = f"{b['fold_range_T_est_frac']:.2f}"
        v["BsMeanErrFold"] = f"{b.get('fold_range_mean_err', float('nan')):.2f}"
        v["BsTauHit"] = f"{list(b['per_beta'].values())[0]['tau_hit']:.3f}"
        v["BsBetaHkT"] = "8"
        src += " + beta_scaling_audit.json"
    return v, src


def wca_sham():
    """WCA matched-sham control macros.  Absent until the run is aggregated."""
    p = os.path.join(ROOT, "results/wca_sham/sham/sham_summary.json")
    if not os.path.exists(p):
        return {}, "results/wca_sham (not yet aggregated)"
    d = json.load(open(p))
    if not d.get("complete", False):
        # An unfinished run must not reach the manuscript. Placeholders are the correct
        # output here: they compile, and they are visibly not a result.
        return {}, ("results/wca_sham (INTERIM -- "
                    f"{len(d.get('seeds', []))} seeds, macros withheld)")
    rows = {r["arm"]: r for r in d["vs_abf"]}
    v = {
        "WcsSeeds": len(d["seeds"]),
        "WcsCell": "b1\\_h2", "WcsSteps": "120\\,000", "WcsReplicas": 1024,
        "WcsRate": "0.10",
        "WcsMismatch": d["sham_mismatches"],
        "WcsVerdict": d["verdict"].split(" -- ")[0],
        "WcsCritOne": "PASS" if d["criterion_1"] else "FAIL",
        "WcsCritTwo": "PASS" if d["criterion_2"] else "FAIL",
    }
    if "fr_estimated" in rows:
        e = rows["fr_estimated"]
        v.update(WcsEstGain=f"{e['pct']:.2f}", WcsEstCIlo=f"{e['ci95'][0]:.2f}",
                 WcsEstCIhi=f"{e['ci95'][1]:.2f}",
                 WcsEstWins=f"{e['wins']}/{e['n_seeds']}",
                 WcsEstEss=f"{e['ess_frac']:.3f}", WcsEstAnc=f"{e['max_anc_frac']:.3f}",
                 WcsEstRoundTrips=f"{e['round_trips']:.0f}")
    if "sham_practical" in rows:
        sp = rows["sham_practical"]
        v.update(WcsShamGain=f"{sp['pct']:+.2f}", WcsShamCIlo=f"{sp['ci95'][0]:.2f}",
                 WcsShamCIhi=f"{sp['ci95'][1]:.2f}",
                 WcsShamCIloNinety=f"{sp['ci90'][0]:.2f}",
                 WcsShamCIhiNinety=f"{sp['ci90'][1]:.2f}",
                 WcsShamRoundTrips=f"{sp['round_trips']:.0f}")
        t = d["tost"].get("sham_practical")
        if t:
            v["WcsShamTost"] = "equivalent" if t["equivalent"] else "not shown equivalent"
    if "fr_oracle" in rows:
        o = rows["fr_oracle"]
        v.update(WcsOracleGain=f"{o['pct']:.2f}", WcsOracleCIlo=f"{o['ci95'][0]:.2f}",
                 WcsOracleCIhi=f"{o['ci95'][1]:.2f}")
    for arm, pre in (("fr_estimated", "WcsDirect"), ("fr_oracle", "WcsOracleDirect")):
        dd = d["direct"].get(arm)
        if dd:
            v[pre] = f"{dd['pct']:.2f}"
            v[pre + "CIlo"] = f"{dd['ci95'][0]:.2f}"
            v[pre + "CIhi"] = f"{dd['ci95'][1]:.2f}"
            if arm == "fr_estimated":
                v["WcsDirectWins"] = f"{dd['wins']}/{dd['n_seeds']}"
    return v, "results/wca_sham/sham/sham_summary.json"


def main():
    os.makedirs(TABLES, exist_ok=True)
    v, s = alanine()
    emit(os.path.join(TABLES, "alanine_numbers.tex"), ALA_MACROS, v, s)
    v, s = valine()
    emit(os.path.join(TABLES, "valine_numbers.tex"), VAL_MACROS, v, s)
    g, s = gateway()
    emit(os.path.join(TABLES, "gateway_numbers.tex"), GW_MACROS, g, s)
    w, s = wca_sham()
    emit(os.path.join(TABLES, "wca_sham_numbers.tex"), WCS_MACROS, w, s)


if __name__ == "__main__":
    main()
