#!/usr/bin/env python
"""Generate and run the frozen v3 online arms.

Frozen protocol: docs/V3_PREREGISTRATION.md (v3.1), Amendments 1-6, Appendix A.

Arm accounting (Amendment 6b): the plain-ABF baseline is already complete and is
the pilot's baseline arm.  This script covers the 3 same-bias controls and the
17 remaining configurations -- 1 + 3 + 17 = 21.

Each arm gets its own config and output root.  Run ids collide across arms by
construction (they encode only method/target/gamma/eta/schedule), so the arm
label is carried in the manifest and attached at assembly time rather than being
inferred from a run id.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import shutil
import subprocess
import sys

REFERENCE = pathlib.Path(
    "results/physical_target_pulse_v2/pilot_70_30/reference/reference_profile.csv")

CAPPED8 = dict(kind="capped", c_cut=8.0, sharpness=2.0)
CAPPED12 = dict(kind="capped", c_cut=12.0, sharpness=2.0)
TEMPERED8 = dict(kind="tempered", gamma_wt=8.0)
FLAT = dict(kind="flat")
PHYSICAL = dict(kind="physical")

# (name, track, role, v3 block, n_particles)
ARMS = [
    # --- Track C same-bias controls (Amendment 6b: these are pilot arms) -----
    ("C_capped8_noFR",   "C", "control", dict(family=CAPPED8,  operator="none"), 256),
    ("C_capped12_noFR",  "C", "control", dict(family=CAPPED12, operator="none"), 256),
    ("C_tempered8_noFR", "C", "control", dict(family=TEMPERED8, operator="none"), 256),
    # --- Track P: full flattening bias, physical target (deliberate mismatch) -
    ("P_BD_pmax0.02", "P", "candidate", dict(family=FLAT, target_family=PHYSICAL,
                                             operator="bd", p_max=0.02), 256),
    ("P_BD_pmax0.05", "P", "candidate", dict(family=FLAT, target_family=PHYSICAL,
                                             operator="bd", p_max=0.05), 256),
    ("P_BD_pmax0.10", "P", "candidate", dict(family=FLAT, target_family=PHYSICAL,
                                             operator="bd", p_max=0.10), 256),
    ("P_FT_rho0.70",  "P", "candidate", dict(family=FLAT, target_family=PHYSICAL,
                                             operator="ft", rho=0.70), 256),
    ("P_FT_rho0.85",  "P", "candidate", dict(family=FLAT, target_family=PHYSICAL,
                                             operator="ft", rho=0.85), 256),
    ("P_oracle_target", "P", "diagnostic", dict(family=FLAT, target_family=PHYSICAL,
                                                operator="ft", rho=0.85,
                                                oracle_target=True), 256),
    # --- Track C candidates ---------------------------------------------------
    ("C_capped8_FT_rho0.70",  "C", "candidate", dict(family=CAPPED8,  operator="ft", rho=0.70), 256),
    ("C_capped8_FT_rho0.85",  "C", "candidate", dict(family=CAPPED8,  operator="ft", rho=0.85), 256),
    ("C_capped12_FT_rho0.70", "C", "candidate", dict(family=CAPPED12, operator="ft", rho=0.70), 256),
    ("C_capped12_FT_rho0.85", "C", "candidate", dict(family=CAPPED12, operator="ft", rho=0.85), 256),
    ("C_tempered8_FT_rho0.85", "C", "candidate", dict(family=TEMPERED8, operator="ft", rho=0.85), 256),
    ("C_flat_FT_rho0.85",      "C", "candidate", dict(family=FLAT, operator="ft", rho=0.85), 256),
    # --- Track C diagnostics --------------------------------------------------
    ("C_capped12_oracle_target", "C", "diagnostic",
     dict(family=CAPPED12, operator="ft", rho=0.85, oracle_target=True), 256),
    ("C_capped12_holdout", "C", "diagnostic",
     dict(family=CAPPED12, operator="ft", rho=0.85,
          clone_policy="holdout", hold_steps=500), 256),
    ("C_capped12_oracle_refresh", "C", "diagnostic",
     dict(family=CAPPED12, operator="ft", rho=0.85,
          clone_policy="oracle_refresh"), 256),
    ("C_capped12_K1024", "C", "diagnostic",
     dict(family=CAPPED12, operator="ft", rho=0.85), 1024),
    # --- Bridge ---------------------------------------------------------------
    ("bridge_consistent_physical", "bridge", "diagnostic",
     dict(family=PHYSICAL, operator="ft", rho=0.85), 256),
]

TEMPLATE = """# Frozen v3 arm: {name} ({track}/{role}).  Generated by run_v3_campaign.py.
experiment_name: v3_{name}
output_root: results/v3/arms/{name}
backend: torch
device: cuda
dtype: float64
batch_size_configs: 8

selection:
  write_generic_best: false

potential:
  x_tilt: 0.1021665783

domain:
  x_min: -3.0
  x_max: 3.0
  y_min: -2.5
  y_max: 3.5
  nx_ref: 801
  ny_ref: 801
  nx_profile: 401

simulation:
  beta: 4.0
  dt: 0.002
  n_particles: {n_particles}
  n_steps: 50000
  eval_every: 500
  seeds: [0, 1, 2, 3, 4, 5, 6, 7]
  x_init_mode: uniform
  y_init_mode: uniform

abf:
  estimator: binned_smooth
  observation_order: post_propagation
  h: 0.05
  update_every: 10
  min_count: 1.0
  ema_alpha: 0.05

fr:
  enabled: false
  target_types: []
  gamma_values: [0.0]
  eta_values: [0.10]
  burnin_fractions: [{burnin}]
  duration_fractions: [{duration}]
  ramp_fraction: 0.0
  fr_every_values: [1]
  noise_chunk_steps: 1000

v3: {v3json}

methods:
  - abf_only
"""


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--only", default=None,
                    help="comma-separated arm names or a role (control/candidate/diagnostic)")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args(argv)

    sel = None
    if args.only:
        sel = set(args.only.split(","))
    manifest = []
    for name, track, role, v3, npart in ARMS:
        if sel and name not in sel and role not in sel and track not in sel:
            continue
        has_fr = v3.get("operator", "none") != "none"
        # The window lives in the v3 block: io_utils hardcodes the RunSpec's
        # burnin/stop for the abf_only method, so it cannot carry the schedule.
        v3full = dict(enabled=True, name=name, fr_stride=500,
                      burnin_fraction=0.2, stop_fraction=0.8, **v3)
        cfg_path = pathlib.Path(f"configs/v3_arm_{name}.yaml")
        cfg_path.write_text(TEMPLATE.format(
            name=name, track=track, role=role, n_particles=npart,
            burnin=0.2 if has_fr else 0.0,
            duration=0.6 if has_fr else 1.0,      # stop_fraction = 0.8 or 1.0
            v3json=json.dumps(v3full)))
        out = pathlib.Path(f"results/v3/arms/{name}")
        (out / "reference").mkdir(parents=True, exist_ok=True)
        shutil.copy(REFERENCE, out / "reference" / "reference_profile.csv")
        manifest.append(dict(arm=name, track=track, role=role,
                             config=str(cfg_path), output_root=str(out),
                             n_particles=npart, has_fr=has_fr, v3=v3full))
        if args.dry_run:
            print(f"[dry] {name:32s} {track}/{role:10s} fr={has_fr} K={npart}")
            continue
        print(f"[campaign] running {name} ({track}/{role})", flush=True)
        r = subprocess.run(
            [sys.executable, "scripts/run_abf_fr_grid_torch.py",
             "--config", str(cfg_path), "--stage", "production_gpu"],
            capture_output=True, text=True)
        tail = r.stdout.strip().splitlines()[-1] if r.stdout.strip() else r.stderr[-400:]
        print(f"[campaign]   {tail}", flush=True)
        if r.returncode != 0:
            print(f"[campaign] FAILED {name}\n{r.stderr[-2000:]}", file=sys.stderr)
            return 1

    mpath = pathlib.Path("results/v3/arms/arm_manifest.json")
    mpath.parent.mkdir(parents=True, exist_ok=True)
    existing = json.loads(mpath.read_text())["arms"] if mpath.exists() else []
    names = {a["arm"] for a in manifest}
    merged = [a for a in existing if a["arm"] not in names] + manifest
    mpath.write_text(json.dumps(dict(n_arms=len(merged), arms=merged), indent=2))
    print(f"[campaign] manifest: {len(merged)} arms -> {mpath}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
